### ISSUE TITLE
Gestione riserve e estensioni da us

### ISSUE THREAD

**Issue by ico88** [CroceRossaCatania/gaia#1017]
Prevedere il rientro da riserva come us, segnalare le estensioni aperte per le quali non è stato richiesto il rientro e permettere di registrare il rientro avvenuto prima della scadenza o la dimissione per mancato rientro

**Comment by PaoloGiustiniani** [comment]
@AngeloLupo anche estensioni.

**Comment by AngeloLupo** [comment]
@PaoloGiustiniani  provvedero'
