### ISSUE TITLE
Problemi quote post ordinario -- > attivo

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1133]
Sdoppiamento quote con problematiche inerenti la contabilità

ICP-184-14133

**Comment by AlfioEmanueleFresta** [comment]
Analizzando il problema con @ico88, pare che il problema post #1914 diventi semplicemente di appartenenza, ovvero, un membro ordinario attivato deve mutare la sua appartenenza in MEMBRO ORDINARIO DIMESSO.
