### ISSUE TITLE
Captcha e diversamente abili

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaCatania/gaia#1210]
sweetcaptcha non permette accesso a diversamente abili con problemi di vista perchè non è possibile effettuare la lettura.

Aggiungere possibilità di usare reCaptcha in questi casi.

**Comment by ico88** [comment]
In reCaptcha non funziona la sintesi vocale, non permette inserimento ne lettura numeri
@AlfioEmanueleFresta

**Comment by dan-it** [comment]
La sintesi vocale a me funziona correttamente solo che:
1. è in inglese (ma non credo reCaptcha supporti audio in italiano)
2. è __impossibile__! Ho fatto qualche prova con altri siti che utilizzano reCaptcha ma qui è infinitamente più complesso. [Esempio semplice](https://www.google.com/recaptcha/api2/demo)

Può essere che la seconda sia dovuto al numero di bot che riceve dal sito?

**Comment by AlfioEmanueleFresta** [comment]
Ciao @dan-it, secondo le FAQ di Google, la complessita' del CAPTCHA da presentare varia in solo rispetto alla reputazione del client. Mi sembra plausibile. Come esempio, effettuando il login tramite navigazione anonima - quindi senza account Google o cronostoria, ottengo sempre un CAPTCHA complesso.
