### ISSUE TITLE
Bug subdolo quote

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaCatania/gaia#1218]
Ci sono alcune situazioni che ingannano la povera query delle quote pagate e in particolare:
* se un utente da attivi viene dimesso e rimane ordinario e paga la quota come ordinario la quota risulta sia in quelle degli ordinari sia in quelle degli attivi
* se un utente paga la quota da 16€ e diventa attivo la cifra di 16€ viene frammentata in due metà: 8€ sul rinnovo da ordinario e 8€ senza dicitura (questo perchè la frammentazione viene fatta sulla base dello stato attuale dell'utente e non sulla base dell'appartenenza su cui è stata pagata la quota)

@AlfioEmanueleFresta e @ico88 so come risolvere la seconda ma mi serve aiuto per risolvere la prima

**Comment by AlfioEmanueleFresta** [comment]
La seguente logica dovrebbe funzionare per l'identificazione del socio attivo **S** nell'anno **Y**:

1. Per ogni appartenenza **A** del socio **S** in ordine strettamente temporale inverso:
  1. Se l'appartenenza ha inizio prima di un anno fa, **ritorna FALSO** e termina;
  2. Se l'appartenenza e' di terminata con dimissione, **ritorna FALSO** e termina;
  3. Per ogni quota **Q** relativa all'appartenenza **A**:
    1. Se la quota e' relativa all'anno **Y**, **ritorna VERO**;
2. **Ritorna FALSO** e termina.

@CroceRossaCatania/sviluppatori e @CroceRossaCatania/supporto potete darmi conferma?

**Comment by ico88** [comment]
Ok per tutto, se sono in stato dimesso ovviamente non compaio nelle quote
da pagare

**Comment by AlfioEmanueleFresta** [comment]
Introduco
```php
// Ritorna l'elenco delle appartenenze passibili al pagamento 
// della Quota associativa per un dato anno
array(Appartenenza) Utente::appartenenzePassibiliQuota($anno = date('Y'));

// Ritorna qualora l'utente sia passibile al pagamento 
// della Quota associativa per un dato anno
bool Utente::passibileQuota($anno = date('Y'));

// Ritorna se il socio e' attivo (ha pagato almeno una Quota associativa nell'anno dato)
bool Utente::socioAttivo($anno = date('Y'));

// Ritorna se il socio e' non attivo (non ha ancora pagato almeno una Quota associativa nell'anno dato)
bool Utente::socioNonAttivo($anno = date('Y'));
```

**Comment by AlfioEmanueleFresta** [comment]
Da migliorare ancora:
1. Controllare se la quota trovata e' statta annullata (in Utente::socioAttivo)
2. Separazione Quote per Volontari e Soci ordinari

**Comment by PaoloGiustiniani** [comment]
Aggiungo YR-905-86253.

Nell'elenco "Quote volontari - PAGATE" risulta indicata la quota del volontario, sia nella sede di apartenenza, sia nella vecchia sede di apaprtenenza.

**Comment by matthewmazzoleni** [comment]
una casistica: "la duplicazione quote nei soci ordinari, avviene solamente per gli ultimi volontari gestiti con la funzione corsi base. i nuovi volontari, divenuti attivi con la procedura corsi base, pagando la quota di socio attivo 2015 si trovano l'indicazione della quota da € 8 sia nell'elenco soci attivi pagate che soci ordinari pagate"

**Comment by matthewmazzoleni** [comment]
una casistica: "La socia ordinaria 104517 ha pagato la quota di 16 euro del 2015, ma tale quota compare sia nell'elenco delle quote pagate dei soci attivi sia nell'elenco delle quote pagate dei soci ordinari (incrementando entrambi gli importi). la ricevuta è stata annullata da US."

**Comment by matthewmazzoleni** [comment]
una casistica (leggermente diversa dalla precedente, sia per la storia del Volontario sia per il fatto che questo è Volontario e non Ordinario):

"Il socio attivo 80927  era prima socio ordinario, poi è stato passato negli attivi il 23/12/2014; ora ha pagato la quota di 8 euro per il 2015 ma tale quota compare sia nelle quote pagate dei soci attivi che nelle quote pagate dei soci ordinari (aumentando entrambi gli importi). la ricevuta è stata annullata da US."

**Comment by matthewmazzoleni** [comment]
78818 e 78022 risulta sia in quote pagate che in quote non pagate

rif: GYT-313-66937

**Comment by ico88** [comment]
Ha due appartenenze per caso ?

**Comment by AlfioEmanueleFresta** [comment]
```sql
ALTER TABLE quote
MODIFY COLUMN appartenenza int(11)
```
