### ISSUE TITLE
Impossibile trasferire volontario

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1288]
rif: ZFO-443-57207

viene permessa l'effettuazione di tutta la trafila (sia con l'utenza del Presidente, che con quella del Delegato Ufficio Soci. Nel momento in cui viene effettuato il salvataggio (del trasferimento), il sistema ripropone la maschera per l'immissione dei dati per un nuovo trasferimento. Se successivamente si entra nella pagina per la conferma del trasferimento, non viene presentato nessun volontario, così come nessuna annotazione è presente sulla scheda del volontario e nessuna attesa di trasferimenti da autorizzare è indicata nel menù a tendina "Presidente"

segni particolari dell'utente: è in estensione, account non attivo.

**Comment by matthewmazzoleni** [comment]
riapro in quanto dai riscontri ricevuti dopo la chiusura del ticket il problema permane.

esempio: il presidente 5778  cerca di trasferire 59753 presso altro comitato, su conferma la finestra viene chiusa e riaperta, non compilata, senza completare l'operazione. operazione effettuata con chrome.

**Comment by ico88** [comment]
Richiesta nuova o vecchia ?
Il 17/Gen/2015 19:06 "Matthew Mazzoleni" <notifications@github.com> ha
scritto:

**Comment by matthewmazzoleni** [comment]
richiesta fatta ieri

**Comment by matthewmazzoleni** [comment]
up: l'errore si presenta tutt'oggi su tentativo di trasferimento di un utente da parte di US, per casi di esempio fare riferimento a tutti i ticket già segnalati sopra

**Comment by matthewmazzoleni** [comment]
up: altro caso. trasferendo 24153 alla conferma dell'operazione viene riaperta la maschera non compilata di trasferimento. questo succede sia a Presidente che Admin.

**Comment by matthewmazzoleni** [comment]
in altro caso trasferimento genera eccezione fatale:

string(56) "Call to undefined method Volontario::invalidaTesserino()"

**Comment by FAmeglio** [comment]
Ora mi succede anche quando chiedo l'estensione a un volontario, clicco estendi e mi riapre la finestra, questa volta relativa al trasferimento, vuota

**Comment by matthewmazzoleni** [comment]
gli utenti segnalano che, a fronte del fix, non riescono comunque a trasferire (né estendere) il volontario 59753
