### ISSUE TITLE
Permettere di inserire un secondo referente di attività

### ISSUE THREAD

**Issue by ico88** [CroceRossaCatania/gaia#1321]
Molte persone vorrebbero avere un secondo referente nell'attività, una specie di referente che può sovrapporsi al primo in caso di eccessivo carico di lavoro

**Comment by giordanotrecca** [comment]
Il CL di Varese si associa a questa esigenza in quanto, in comitati grandi, lo staff che si creano i delegati e i referenti di attività possono essere notevoli.
Concordo con voi che è meglio un solo referente che crea le attività e i turni e collaboratori/staff che gestiscono conferme/rifiuti/inserimenti di partecipazioni.
Ciao e grazie

**Comment by AlfioEmanueleFresta** [comment]
Questo e' stato inserito nelle esigenze degli interessati in `jorvik` e verra' realizzato.
