### ISSUE TITLE
Richiesta estensioni utenti Safari

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1351]
Siete a conoscenze di problematiche riguardo la richiesta di estensione con safari?

Potrebbe essere un problema di javascript?

Vanno tutte in errore.

ACQ-667-41644

**Comment by AlfioEmanueleFresta** [comment]
Dopo testing con Safari viene fuori che Safari non rispetta il tag required HTML5. Lasciando il campo motivo vuoto viene mostrato un errore generico.
