### ISSUE TITLE
Autoparco filtraggio per autoparchi

### ISSUE THREAD

**Issue by ico88** [CroceRossaCatania/gaia#1392]
Permettere visualizzazione dei veicoli presenti su singolo autoparco

**Comment by AngeloLupo** [comment]
Bisogna aggiungere la possibilita' di filtrare per autoparchi e per tipo di veicolo.
Va inoltre considerato che l'utente potrebbe voler utilizzare piu' di un filtro alla volta, quindi i nomi delle classi vanno scelti con particolare attenzione.
@AlfioEmanueleFresta qual'e' il modo piu' efficiente di selezionare tutti gli autoparchi di un dato comitato?

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo usa questa funzione
https://github.com/CroceRossaCatania/gaia/blob/master/core/class/Utente.php#L705
