### ISSUE TITLE
trasferimento approvato ma richiesto nel 1970

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1494]
rif: GRI-933-95129

l'utente ha ricevuto conferma trasferimento ma nella mail la richiesta risulta inoltrata il 01/01/1970.
la richiesta in realtà è stata avviata il 18 set.

**Comment by PaoloGiustiniani** [comment]
https://github.com/CroceRossaCatania/gaia/pull/2092 risolve, o sbaglio?

**Comment by luca-dex** [comment]
No, non risolve. Dovreste modificare tutti gli inserimenti di date in giro per il codice di gaia con la funzione  `daFormato` per essere sicuri di non avere più problemi di questo tipo. :smile:

**Comment by PaoloGiustiniani** [comment]
@luca-dex grazie mille.

@AlfioEmanueleFresta please.

**Comment by matthewmazzoleni** [comment]
aumentano segnalazioni
