### ISSUE TITLE
Data versamento quota corrisponde a data inserimento su GAIA

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#1548]
Ho verificato che dopo aver aggiunto i soci ordinari e quindi le quote associative, nello storico delle quote pagate visibile da US non viene mostrata la data di pagamento ma la data in cui è stato inserito il pagamento su GAIA.
Ad esempio gli ordinari ID 85640, 85641 e 85642 risultano tutti aver pagato "oggi" quando "oggi" è la data di inserimento su GAIA.

**Comment by PaoloGiustiniani** [comment]
@CroceRossaCatania/sviluppatori bisognerebbe dare priorità a questa issue in quanto siamo in pieno tesseramento.

Inoltre è essenziale che sulla ricevuta vengano mostrati due dati:
1) data di registrazione pagamento 
2) data di pagamento

**Comment by AlfioEmanueleFresta** [comment]
Unito in #1904.
