### ISSUE TITLE
[autoparco] errore: veicolo già presente

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1561]
L'inserimento dei veicolo con targa CRI572AD fallisce in continuazione fornendo l'errore in oggetto.

Dalla lista non risulta, già flushato la cache.

LIQ-227-13667

**Comment by AngeloLupo** [comment]
@PaoloGiustiniani Ho appena riprovato con @AlfioEmanueleFresta, siamo riusciti ad inserire il veicolo

**Comment by PaoloGiustiniani** [comment]
L'utente riferisce che la casistica persiste.

**Comment by PaoloGiustiniani** [comment]
La casistica persiste " Veicolo presente. Il Veicolo è già presente in elenco.".

Basta semplicemente tentare un inserimento in produzione per replicare l'errore.

L'utente sta sollecitando.

**Comment by ico88** [comment]
Numero targa e telaio siamo sicuri non siano in db?

**Comment by PaoloGiustiniani** [comment]
Il problema era legato al libretto.

E' opportuno dettagliare l'errore specifico riscontrato.
