### ISSUE TITLE
Volontari non vengono mostrati in un'attività

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#1580]
Nonostante conferma di partecipazione, i volontari non vengono mostrati come partecipanti all'attività.
Se aggiungo manualmente i volontari che avevano dato disponibilità, non vengono mostrati lo stesso.
ID attività 3881

**Comment by AlfioEmanueleFresta** [comment]
Al momento attuale l'attivita' in questione non ha partecipazioni rotte e solo un turno. Non riproducibile.
