### ISSUE TITLE
[aspiranti] Selettore direttore corso

### ISSUE THREAD

**Issue by biagiosaitta** [CroceRossaCatania/gaia#1600]
non è possibile scegliere un direttore del corso dello stesso comitato organizzatore ma di una unità territoriale diversa da quella organizzatrice.

**Comment by biagiosaitta** [comment]
@AlfioEmanueleFresta si può sistemare questa cosa?

**Comment by AlfioEmanueleFresta** [comment]
@biagiosaitta @ico88 qual e' la giustificazione per il comportamento da te desiderato?

**Comment by biagiosaitta** [comment]
Un direttore di un corso, di una unità territoriale diversa dalla sua, ma all'interno dello stesso comitato, dovrebbe poter essere nominato senza bisogno di essere esteso su qualla unità territoriale. Giusto @PaoloGiustiniani ?

**Comment by PaoloGiustiniani** [comment]
Confermo

**Comment by matthewmazzoleni** [comment]
abbiamo diverse segnalazioni per questo selettore bloccato all'unità territoriale e non al CL/CP

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni ho effettuato la modifica richiesta, in produzione. Potresti cortesemente verificare la bonta' della modifica per almeno un utente e dare eventualmente risposta di risoluzione. Grazie mille. @CroceRossaCatania/supporto fyi.
