### ISSUE TITLE
Trasferimento massivo volontari da csv

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1650]
E' opportuno prevedere un import che effettui l'operazione in oggetto.

Credo che il file debba avere questa struttura
CodiceFiscale - VecchioComitato - NuovoComitato

L'operazione dovrà prevedere l'aggiornamento dello storico con relativo aggiornamento dell'appartenenza.

L'operazione dovrà prevedere la normale procedura di trasferimento qualora lo spostamento sia al di fuori del comitato richiedente es. locale > provinciale

Criticità? Penso nella generazione degli elenchi / quote

**Comment by matthewmazzoleni** [comment]
up: abbiamo interi CP da smembrare in CL neocostituiti, e aumentano

**Comment by ico88** [comment]
Tutto si base su unità territoriale o al massimo oid ma se facciamo un assembla comitati, mi spiego;
- CP

-- CL1
---UL1.1

-- CL2
---UL2.1

Posso unire tutto quello che ci sta in UL1.1 su UL2.1 e posso spostarli su più locali.
Oppure direttamente se dico di unire CL1 su CL2 diventerà così:

- CP
-- CL2 con dati del CL1
-- UL1.1
-- UL2.1

Confermate?

**Comment by matthewmazzoleni** [comment]
ti faccio l'esempio di richieste che abbiamo:
- fondere UL di stesso comitato (assemblandole tutte su una, o creandone una nuova, forse meglio)
- fondere CL tra loro (e relative UL)
- convogliare volontari di intere UL (di CL o CP) in nuovi CL neocostituiti (esempio tipico territori dove c'era un CP con molte UL e le si sta convogliando per zona in nuovi CL)

**Comment by matthewmazzoleni** [comment]
up: utenti chiedono feedback per le richieste effettuare a novembre sul convoglio di utenti nei nuovi comitati
