### ISSUE TITLE
[accademia] Progettazione (requisiti)

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaCatania/gaia#1659]
Lo scopo di questo issue e' quello di raccogliere tutte le risorse che abbiamo per la progettazione del modulo "Accademia" e metter giu' per bene i requisiti formali del modulo.

Direi che per iniziare e' il caso di raccogliere tutti i regolamenti e documenti che abbiamo fino ad ora
@CroceRossaCatania/sviluppatori

**Comment by ico88** [comment]
@AlfioEmanueleFresta mi dai manforte che inizio ?

**Comment by AlfioEmanueleFresta** [comment]
@ico88 sto lavorando ad un'idea - ti faccio un diagramma su CroceRossaItaliana/gaia-progettazione e torno.

**Comment by ico88** [comment]
Ooook

**Comment by AlfioEmanueleFresta** [comment]
In Jorvik.
