### ISSUE TITLE
volontario dimesso non presente in elenco

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1681]
un volontario dimesso per decesso non figura nell'elenco dei soci dimessi.

i riferimenti della persona sono presenti qui: FDJ-926-21882

**Comment by ico88** [comment]
@matthewmazzoleni correggiamo il caso manualmente e vediamo se si ripresentano altri

**Comment by nicolasbandini** [comment]
Sono il Presidente del CL in oggetto, news sul Volontario? Il fascicolo è stato archiviato da tempo e non abbiamo il CF, vorrei sapere se quindi mi è possibile vederlo su gaia oppure no. Grazie
