### ISSUE TITLE
possibilità di eliminazione/modifica rifornimenti

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1704]
utenti chiedono la possibilità di eliminare un rifornimento errato in autoparco. provando a modificare rifornimento precedente ottengono: "Km sembrano errati. Attenzione il rifornimento che stai cercando di registrare ha dei km inferiori rispetto l'ultimo registrato." quando cercano di correggere i KM

**Comment by ico88** [comment]
Up

**Comment by matthewmazzoleni** [comment]
up

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo qual e' lo stato dell'issue al meglio della tua conoscenza? Se mi fai sapere me lo prendo in carico.
