### ISSUE TITLE
[ufficio soci] delega rimossa ma risultano ancora i permessi

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1722]
L'utente 21712, nonostante sia stato rimosso come delegato ufficio soci per il comitato Locale:176, continua ad avere i privilegi.

presidente.incarichi.visualizza&id=21712 > Attuale > ATTIVO

MBO-279-36778

**Comment by matthewmazzoleni** [comment]
aggiungo anche delega US terminata ma rimasta attiva: 4866

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni 4866 ha due deleghe di cui una non terminata.
