### ISSUE TITLE
[provvedimenti2] delegato espulso risulta negli incarichi

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#1731]
dopo espulsione volontario con deleghe, nei dettagli del comitato [presidente.comitato&oid=xxx] il volontario risulta ancora "Attualmente in carica" e cliccando sul nominativo si leggono solo cognome e nome

**Comment by ico88** [comment]
Testato funziona, riprovate anche voi

**Comment by ico88** [comment]
Chiudo se ripresenta riapriamo
