### ISSUE TITLE
[quote] Socio ordinario mostrato anche tra i soci attivi

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1732]
E' il caso del volontario 53670

Compare sia in 

https://gaia.cri.it/index.php?p=us.quoteSi

Che in

https://gaia.cri.it/index.php?p=us.quoteSi.ordinari

In appartenenze posso dirvi che è stato dimesso e successivamente inserito come ordinario, la quota registrata è solo una.

NPP-333-22292

**Comment by FAmeglio** [comment]
Succede anche a me per i soci 13007 e 13086.
Anche loro erano attive e poi dimesse il 1 maggio 2014

**Comment by livodario** [comment]
A me succede per due soci che nel 2014 hanno pagato la quota come ordinari (corso base) e poi promossi attivi dopo l'esame.
Ora che è stata registrata la quota 2015 come soci attivi compaiono sia nella lista Volontari che Soci Ordinari.

**Comment by PaoloGiustiniani** [comment]
Ciao @livodario,
grazie per il feedback. 

Ti invitiamo a segnalarlo al nostro supporto, per una questione di tracciabilità, qualora non lo avessi ancora effettuato.

Grazie.

**Comment by matthewmazzoleni** [comment]
aggiunto utente 75955, anche esso compare doppio

**Comment by PaoloGiustiniani** [comment]
Aggiungo FVB-584-61705

**Comment by PaoloGiustiniani** [comment]
Aggiungo WHB-662-55173 --> 53414

**Comment by PaoloGiustiniani** [comment]
KDF-229-77579 -> 62439

**Comment by PaoloGiustiniani** [comment]
MDZ-634-61142 > 11176
