### ISSUE TITLE
[tesserino] Richiesta fototessera nonostante sia presente

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1738]
ID Utente per il quale è in corso la richiesta del tesserino 56193 
ID Utente che compie l'operazione 30216 

WTS-833-40298

Messaggio di errore
Per poter generare il tesserino è necessario che l'utente abbia una fototessera caricata e approvata.

Confermo che la foto tessera risulta essere presente.

**Comment by ico88** [comment]
Persiste ?

**Comment by matthewmazzoleni** [comment]
si @ico88
