### ISSUE TITLE
notifica per corso già terminato

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1743]
oggi via email è stata notificata la partenza di un corso datato 22 nov 2014 (BASE-2014/40), corso oltretutto già terminato (oltre che partito). l'aspirante che ha ricevuto la mail è 77889

rif: TPK-980-62516

**Comment by AlfioEmanueleFresta** [comment]
Non riesco a riprodurre. @matthewmazzoleni per favore segnala nuove iterazioni. Fino ad allora e' da considerare un messaggio rimasto in coda di invio troppo a lungo.
