### ISSUE TITLE
[autoparco] inserimento rifornimenti restituisce errore

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1748]
Errore riportato:
"Km sembrano errati. Attenzione il rifornimento che stai cercando di registrare ha dei km inferiori rispetto l'ultimo registrato."

Gli utenti non hanno la possibilità di inserire rifornimenti antecedenti rispetto all'ultima data di rifornimento.

Es.: Ultimo rifornimento del 25/12/2014

Se per caso volessi registrare anche un rifornimento del 24/12/2014 con KM inferiori rispetto a quelli del 25/12/2014 il sistema non lo permette.

Nel ticket sono presenti tutti i dettagli: XNC-407-35771

**Comment by AlfioEmanueleFresta** [comment]
@PaoloGiustiniani e @AngeloLupo riusciamo ad organizzare un hangout per risolvere questo problema? Alternativamente bisogna ottenere i dati esatti che e' intenzione inserire e lavorare su quelli per riprodurre.

**Comment by PaoloGiustiniani** [comment]
Ho tutti i dati che servono.

Schedula e ci sono.

**Comment by AngeloLupo** [comment]
@PaoloGiustiniani @AlfioEmanueleFresta preferibilmente dopo giorno 7

**Comment by PaoloGiustiniani** [comment]
Altro caso ZQJ-583-66783
