### ISSUE TITLE
[aspiranti] Data ingresso in CRI coincide con data generazione verbale e non con data esame

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#1750]
La data di ingresso coincide con la data in cui viene generato il verbale con GAIA e non con la data in cui è stato fatto l'esame (anche se in realtà dovrebbero coincidere)
Ad esempio utente ID 83798

**Comment by ico88** [comment]
up

**Comment by matthewmazzoleni** [comment]
up

**Comment by FAmeglio** [comment]
Il problema sorge dal fatto che l'esame viene a volte fatto in due sessioni e, dato che gaia non permette questa cosa, viene fatto il verbale dopo tutte le sessioni..
