### ISSUE TITLE
[tesserini] Se fototessera negata, inserire motivazione e link ai criteri 

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#1753]
Quando viene negata una fototessera da US o Presidente, sarebbe utile poter inserire la motivazione e nella mail che arriva al volontario anche il link ai criteri per caricare una fototessera corretta.

**Comment by ico88** [comment]
A mio avviso il motivo per cui si possa negare la fototessera è solo uno, ovvero, la non conformità con i criteri.
Basta modificare la mail di negazione e inserire i riferimenti ai criteri
