### ISSUE TITLE
generazione excel soci attivi causa errore fatale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1755]
p=admin.utenti.excel richiamato da utente 63417 genera errore fatale 54a17b869b7fd20c16c264e8

nota: l'utente è Volontario in un CP della Lombardia, esteso in un comitato della regione Piemonte. In Piemonte risulta in US regionale.

**Comment by ico88** [comment]
Confluisce in #1769
