### ISSUE TITLE
login a gaia non funzionante

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1757]
molti utenti segnalano che, dopo il reset password o a fronte di nuovo attivazione account, non possono più accedere a GAIA per errore di password errata. ho cambiato manualmente la password all'utente 5909 che segnalava il problema e in effetti anche con il cambio non riesco a fare login.

il problema è già stato segnalato da più utenti

rif: OGP-239-97965

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni ho testato le funzionalita' di ripristino password e funzionano correttamente.

Nel caso dell'utente 5909, risultano due utenze con la stessa email - possibilmente da un errato import (o magari son marito e moglie). Ti chiedo di risolvere la situazione con gli utenti - forse una chiamata all'US o agli utenti stessi e' la migliore soluzione.

Puoi trovare le due utenze cercando l'email dell'utente, i primi due risultati (dello stesso comitato) son le due utenze che condividono la mail.
