### ISSUE TITLE
[tesserini] emessi in occasione di jump non censiti

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1759]
Lato ufficio soci ci segnalano che qualche giorno fa risultava la dicitura "Emesso il.." mentre ora l'unico tasto che compare è quello per la richiesta di emissione.

Utente 55138

**Comment by AlfioEmanueleFresta** [comment]
@ico88 che operazioni hai effettuato sul database?

**Comment by ico88** [comment]
@AlfioEmanueleFresta Aggiunta del tipo nel db che era a null mentre va valorizzato come emissione

**Comment by AlfioEmanueleFresta** [comment]
Non riproducibile.
