### ISSUE TITLE
errore fatale su caricamento csv (apparentemente senza motivo)

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1762]
mentre si cerca di caricare utenti con il flusso viene dato (appartentemente in modo randomico) questo errore, i dati sembrano ok nel csv: 54a6eb519b7fd2c552673402

object(MongoId)#12 (1) {
  ["$id"]=>
  string(24) "54a6eb519b7fd2c552673402"
}

string(56) "Call to a member function getTimestamp() on a non-object"

string(51) "/home/gaia/public_html/gaia/inc/admin.format.ok.php"

**Comment by ico88** [comment]
Controllare bene spazie e date

Il giorno 2 gennaio 2015 20:07, matthewmazzoleni <notifications@github.com>
ha scritto:

**Comment by AlfioEmanueleFresta** [comment]
Quell'errore deriva da una eccezione non gestita relativamente ad una data in un formato non expectato. Non un bug ma sarebbe gestibile diversamente.
