### ISSUE TITLE
[trasferimenti] richiesta in attesa ma non risulta da approvare

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1763]
Abbiamo diverse richieste di trasferimento tra unità di uno stesso comitato provinciale.

Le stesse risultano correttamente in attesa ma non è possibile approvarle/protocollarle in quanto non risultano tra le richieste in attesa.

Esempio: utente 53477

In presidente.trasferimento non c'è traccia.

**Comment by ico88** [comment]
accedi come us o come presidente ?

**Comment by ico88** [comment]
Si era bloccato per qualche strano il meccanismo ho solo forzato a rifare, risultava protocollata e anche approvata ma non l'appartenenza.

**Comment by PaoloGiustiniani** [comment]
Sarebbe da fare anche per

53476 
58119
53467
53431 
53431 
53416 
53412 
53405 
53341 
53318

**Comment by ico88** [comment]
Sono richieste nuove o vecchie ?

**Comment by ico88** [comment]
Sistemate quelle da sistemare, ovviamente se avevano estensioni devono rifarle

**Comment by PaoloGiustiniani** [comment]
anche questa, sempre vecchia

53459 

poi abbiamo finito.

**Comment by ico88** [comment]
Risolto
