### ISSUE TITLE
modifica campi veicolo non consentita (rif: #1756)

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1767]
come da #1756 dopo test (sia admin che dell'utente) non è possibile salvare il dato modificato.

riapro quindi specificando che l'anomalia è sia lato utente che lato admin.

grazie,

**Comment by ico88** [comment]
Perché utente dovrebbe modificare ? Solo per correzione errori ?

**Comment by matthewmazzoleni** [comment]
@ico88 ipotizzo di sì, in ogni caso anche da admin il salvataggio non avviene
