### ISSUE TITLE
[elenco soci] generazione genera errore fatale

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1769]
54a8e9869b7fd2ff6b2c4cb8 (string(50) "Call to a member function format() on a non-object")

YQJ-956-88311

Utente: 8342

**Comment by ico88** [comment]
Problema anagrafico, andrebbe aggiunta una eccezione per impedire il fallimento

**Comment by ico88** [comment]
Io riesco a generare l'elenco soci tranquillamente
