### ISSUE TITLE
[ordinario] inserimento nuovo socio fallisce

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1770]
Tutti i dati per replicare l'errore sono presenti nel ticket BEH-416-71939

54a95be69b7fd2e175986d1d
string(50) "Call to a member function inizio() on a non-object"

Data pagamento quota 04/01/2015

**Comment by ico88** [comment]
@PaoloGiustiniani basta aprire il tesseramento 2015 e funziona tutto correttamente
