### ISSUE TITLE
Errore generico ad ogni intervento su un utente

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1771]
quando si cerca di dimettere l'utente 76417 viene mostrato errore generico.
cercando di utilizzare il selettore utenti del form di assistenza per selezionare 76417 la maschera va in errore 54ab28069b7fd2dd5e40ea29

nota: visionando l'anagrafica risulta inserito un carattere anomalo nel nome (cosa diffusa per le importazione xls, causa lettere accentate nei dati che non sono state interpretate correttamente in fase di import).

per replicare:
- loggarsi come 33787 
- provare a dimettere 76417
- provare ad aprire ticket di supporto selezionando 76417

rif: HLN-209-16889

**Comment by ico88** [comment]
Carattere totalmente a cavolo, provate dimissione ora
