### ISSUE TITLE
[tesserini] funzionamento anomalo pagina presidente.soci.ok

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1772]
Lato US risultano le seguenti situazioni:

- In presidente.soci.ok è mostrato il pulsante "tesserino" (che rinominerei in "richiedi tesserino", per far capire l'azione che viene scatenata al click) anche per volontari che hanno fototessera caricata ma non approvata.
- in presidente.soci.ok, a fianco di un Volontario con regolare tesserino emesso a dicembre (indicato nella colonna dedicata), non è presente il tasto "Richiedi duplicato"

per replicare:
- loggarsi come 2054
- impostare ruolo ufficio soci.
- aprire elenco soci
- l'utente 20231 ha tesserino emesso ma non presente pulsante duplicato
- l'utente 24047 non ha tesserino approvato ma viene mostrato il pulsante "tesserino" (c.d. "richiedi tesserino")

**Comment by ico88** [comment]
Vero tutto errore nel codice il duplicato lo chiede livello inferiore non regionale vedo di sistemaro se poi mi fate dei test mergiamo
