### ISSUE TITLE
[aspiranti] pulsante di registrazione a GAIA su pagine corsi

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1773]
Alcuni comitati pubblicizzano il corso per Volontari indicando l'url del corso su GAIA. Ci viene segnalato che, però, non è molto intuitivo il passaggio che l'utente deve fare per iscriversi. Arrivando in modo non autenticato sulla pagina può visionare le informazioni ma non ha un pulsante visibile che gli permetta la registrazione al sistema. Esso deve andare alla Home di GAIA, scegliere la modalità di iscrizione al portale e portare a termine il processo. Sarebbe utile avere un bottone direttamente nella pagina del corso, così da permettere facilmente il redirect alla pagina di registrazione aspirante.

**Comment by ico88** [comment]
Direi che è una ottima idea
