### ISSUE TITLE
Elimina sede non possibile nonostante assenza di Soci

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1774]
Da admin provando ad eliminare sedi territoriali a cui non sono afferenti Soci approvati il sistema blocca l'operazione indicando invece la presenza di Soci. Generando gli elenchi xls risulta che la sede attualmente non ha persone associate.

Propongo che l'eliminazione (nei casi in cui effettivamente abbia senso rispetto ad un accorpamento come indicato da #1521), dopo aver verificato la non presenza di soci approvati:
- elimini le appartenenze in attesa
- pulisca servizi, nomine, gruppi, corsi, autoparchi, etc...

questa operazione ovviamente rimane per utilizzi tecnici, nel caso normale (anche solo per lo storico del tutto) le sedi saranno da fondere.

rif: OLZ-225-98206

**Comment by ico88** [comment]
Più che eliminazione farei quanto suggerito da @AlfioEmanueleFresta ovvero la disattivazione del comitato con conseguente fusione come da te indicato.
Così manteniamo integrità

**Comment by ico88** [comment]
Se appartenenza valida allora non faccio nulla, se appartenenza in attesa la cancello, tutto il resto cancello
