### ISSUE TITLE
Errore nell'apertura di presidente.comitato&oid=Comitato:52

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1776]
Il presidente segnala che, all'apertura della pagina relativa alla sede territoriale in oggetto, il sistema genera errore fatale

errore 54acf0709b7fd246700550db
string(100) "Uncaught 20150107093808 [ERR #1003]: Entità non presente (tabella:id) =>     anagrafica:1060

rif: CTS-229-78734

**Comment by ico88** [comment]
Controllate in db le deleghe su quel comitato

**Comment by ico88** [comment]
Risolto
