### ISSUE TITLE
Generazione tesserini in caso di non compilazione dati comitato

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1777]
In caso di mancata compilazione dei dati del comitato (che vengono stampati sul tesserino) dovrebbe in qualche modo essere negata la possibilità di generare la richiesta

di stampa da parte di US e Presidente

**Comment by matthewmazzoleni** [comment]
up: un CR ha fatto una prova di generazione tesserini e si è accorto dell'anomalia
