### ISSUE TITLE
[gaia] Registrazione con Codice Fiscale già presente

### ISSUE THREAD

**Issue by biagiosaitta** [CroceRossaCatania/gaia#1778]
Nonostante il codice fiscale dell'anagrafica 2106 sià già registrato, se si prova a registrarsi nuovamente con lo stesso codice fiscale il sistema non indica che l'anagrafica è già presente ma fa proseguire con la registrazione modificandone i dati!

**Comment by AlfioEmanueleFresta** [comment]
@biagiosaitta il volontario in questione ha una password di accesso assegnata?

**Comment by ico88** [comment]
Confermo che è senza password

**Comment by AlfioEmanueleFresta** [comment]
@biagiosaitta le persone senza password non hanno terminato la registrazione.

**Comment by biagiosaitta** [comment]
Lui aveva completato la registrazione è accedeva tranquillamente. Poi forse per qualche reset non andato a buon fine il campo password si è settato a NULL
