### ISSUE TITLE
[turni] apertura ?p=attivita.scheda&id=4107 genera errore fatale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1787]
aprendo la pagina in oggetto si ottiene 

54b0115d9b7fd234751a4a34

string(109) "Uncaught 20150109183525 [ERR #1000]: Errore non documentato - fare riferimento al supporto tecnico	

  thrown"

**Comment by PaoloGiustiniani** [comment]
Lato db non trovo duplicati o anagrafiche corrotte.

**Comment by ico88** [comment]
Eventuali dati tronchi possono essere in aree, partecipazioni, turni, autorizzazioni

**Comment by ico88** [comment]
Riparata, la visibilità era inferiore al livello di creazione
visibilità unità territoriale, livello creazione locale
