### ISSUE TITLE
In utente.password non vengono indicati i criteri per la password

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#1788]
In https://gaia.cri.it/index.php?p=utente.password se viene inserita una password senza rispettarne i criteri appare il messaggio "Inserire un valore nel formato richiesto" ma non viene specificato qual'è il formato richiesto (lunghezza minima, presenza carattere numerico, ecc)

**Comment by PaoloAgresti** [comment]
Inserire:
"Scegli una password che abbia tra 8 e 15 caratteri e usa, se possibile, lettere maiuscole, minuscole e numeri.

Ti consigliamo di non usare la password che giù utilizzi per altri account."

**Comment by PaoloGiustiniani** [comment]
@CroceRossaCatania/sviluppatori potreste verificare i requisiti richiesti lato codice?

**Comment by ico88** [comment]
@PaoloAgresti @PaoloGiustiniani lunghezza compresa 8/15 caratteri, consigliabile uso di caratteri alfanumerici non obbligatorio da lato codice però
