### ISSUE TITLE
Presidente ottiene errore aprendo anagrafiche

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1793]
il presidente 12569 ottiene 54b167cc9b7fd2b37e375c6f aprendo tutte le anagrafiche del suo comitato. ad esempio l'anagrafica di 98557.

string(100) "Uncaught 20150110185628 [ERR #1003]: Entità non presente (tabella:id) => 	anagrafica:{id}"

ticket: SFE-726-56697

**Comment by ico88** [comment]
La problematica non mi risulta sembra risolta
