### ISSUE TITLE
[tesserini] contatore non mostra numero esatto

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1794]
Il contatore delle fototessere in attesa di approvazione non mostra il numero corretto.

per simulare potete fare login con utente 2054 (Ufficio Soci) e visionare che il numero supera di alcune unità le vere fototessere presenti in p=presidente.fototessere.pending

**Comment by ico88** [comment]
Parliamo di fototessere  vero ?

**Comment by matthewmazzoleni** [comment]
si @ico88 , scusami errore di digitazione

**Comment by ico88** [comment]
Ok verifico
