### ISSUE TITLE
[attività] notifiche errate

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1804]
Nella email inviata all'utente la variabile _REFERENTE non viene valorizzata (è stato rimosso da _REFERENTE)

Inoltre la mail giunge anche all'utente che ha rimosso il commento.

L'iter corretto dovrebbe essere:
Rimosso da referente > Notifico l'utente
Rimosso da utente > Notifico il referente 

Rif ZZR-152-17486

**Comment by ico88** [comment]
Per referente avevo già provveduto, ora verifichiamo
