### ISSUE TITLE
[permessi] volontario viene mostrato ad ex comitato di appartenenza

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1809]
Il volontario 4873 viene mostrato nelle liste dei volontari in estensione di un comitato a cui non appartiene più.

Info nel ticket CEO-207-83771

**Comment by ico88** [comment]
Mi dai maggiori dettagli perchè ha 3 appartenenze da indagare

**Comment by PaoloGiustiniani** [comment]
Mmhh che tipo di dettagli ti servono?

**Comment by ico88** [comment]
@PaoloGiustiniani la problematica persiste ? se si riapriamo ticket
