### ISSUE TITLE
 [tesserini] possibilità di rimozione foto tessera ad us

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1811]
E' opportuno implementare la funzionalità in oggetto.

Sono giunte numerose segnalazioni a riguardo.

Oltre che rimuovere la foto tessera dovrà verifica se sono presenti richieste in corso di tesserini e gestire la casistica (notifiche via email incluse).

**Comment by ico88** [comment]
Perché rimuovere se possono sostituire ?

**Comment by ico88** [comment]
up

**Comment by matthewmazzoleni** [comment]
@ico88 causa errore di approvazione. aumentano richieste in tal senso
