### ISSUE TITLE
riammissione socio non da conferma

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#1813]
[us.utente.riammetti] non fornisce alcun tipo di messaggio o conferma (pagina bianca) nonostante il volontario venga riammesso correttamente

**Comment by PaoloGiustiniani** [comment]
E' un po' generico.

ID del volontario?

**Comment by GiovanniLongo** [comment]
Provato sulla beta dimettendo un po di gente con le motivazioni che permettono riamissione... di nessuno di quelli riammessi è comparso alcun dato.

**Comment by PaoloGiustiniani** [comment]
ID per favore

**Comment by GiovanniLongo** [comment]
ID 10099, appena dimesso x mancato turno e riammesso senza nessun messaggio di conferma o riepilogo
