### ISSUE TITLE
invio mail senza oggetto fa sparire tasto invio

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#1814]
[utente.mail.nuova] sia su invio singolo, che su invio di massa, se non si inserisce oggetto scompare tasto verde di invio e-mail e compare "attendere..."

**Comment by AlfioEmanueleFresta** [comment]
In realta' il tasto "Attendere..." e' sempre il tasto di invio. Dopo il click cambiamo il testo in attendere per evitare che la gente clicchi piu' volte ed invii nuovamente il form. In questo caso' pero' l'invio non avviene perche' un campo e vuoto, ma il testo del tasto non viene ripristinato - questo e' un problema.

**Comment by GiovanniLongo** [comment]
nella beta, Attendere con "icon-warning-sign" è solo testuale, non è un bottone e la mail non viene inviata
