### ISSUE TITLE
rimozione checked "CM" non viene salvata

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1815]
la rimozione del checked "Corpo Militare" non viene salvata alla pressione del tasto Salva.

rif: NZM-929-77296

**Comment by ico88** [comment]
Admin o us, non è in conto che si possa modificare

2015-01-17 0:34 GMT+01:00 Matthew Mazzoleni <notifications@github.com>:

**Comment by matthewmazzoleni** [comment]
Riscontrato da presidente e verificato anche da admin
