### ISSUE TITLE
[beta] errore non documentato 

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#1817]
Fatal error: Uncaught 20150118021242 [ERR #1000]: Errore non documentato - fare riferimento al supporto tecnico thrown in /home/federico.durso/gaia/core/class/Attivita.php on line 273

attivita.scheda&id=4063

**Comment by ico88** [comment]
Errore di db nella beta non ha molta importanza
Il 18/Gen/2015 02:20 "Giovanni" <notifications@github.com> ha scritto:
