### ISSUE TITLE
[beta] creazione attività da delegato locale fa selezionare tutte unità della provincia

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#1818]
[attivita.comitato] alla selezione del comitato organizzatore (con delega locale attivata), permette di selezionare qualsiasi comitato della provincia

**Comment by ico88** [comment]
Verifichiamo in produzione ?
Il 18/Gen/2015 02:23 "Giovanni" <notifications@github.com> ha scritto:

**Comment by ico88** [comment]
@matthewmazzoleni mi verifichi in produzione questa roba ?
