### ISSUE TITLE
[tesserini] errore di mancata fototessera approvata in generazione tesserino

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1823]
Il presidente 11412 generando il tesserino per 10126 (volontario approvato con fototessera caricata da ufficio soci) riceve il messaggio "Impossibile generare il tesserino. Per poter generare il tesserino è necessario che l'utente abbia una fototessera caricata e approvata."

rif: TGO-654-35707

**Comment by matthewmazzoleni** [comment]
aumentano segnalazioni di uffici soci

**Comment by PaoloGiustiniani** [comment]
Nuova segnalazione STN-710-30345

**Comment by AlfioEmanueleFresta** [comment]
Risolto con ad71573ef840e228470e943f1f66feea44ce373e
