### ISSUE TITLE
[produzione] download elenco titoli con " : " in filename impedisce apertura

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#1825]
rif ticket [SCE-671-80784] 

ipotizzo vada rimosso il " : " dal nome file che risulta incompatibile con il filename nel filesystem fat/ntfs

"Risultati in Comitato Locale di Xxxxxx: Xxxxxx.xls"

sostituire con " - " ?

**Comment by ico88** [comment]
@GiovanniLongo io sono riuscito a scaricare e farlo andare con libre office, a te che problema dava esattamente ? falliva apertura ?

**Comment by ico88** [comment]
errore di link nell'issue

**Comment by AlfioEmanueleFresta** [comment]
Confermo. Il carattere `:` non e' valido nei file system di windows. Generalmente i browser son abbastanza bravi a risolvere la problematica, sostituendo i caratteri prima di scaricare il file su disco. Alcuni gestori di archivi compressi son in grado di fare lo stesso, ma non e' corretto fare affidamento su questa feature. Provvedo.

**Comment by AlfioEmanueleFresta** [comment]
@GiovanniLongo per favore informa l'utente.

**Comment by matthewmazzoleni** [comment]
riapro in quanto l'utente segnala ancora problemi, trovate il file incriminato qui: SCE-671-80784

**Comment by AlfioEmanueleFresta** [comment]
Hai ragione @matthewmazzoleni. La mia patch era mirata ai nomi dei file scaricati direttamente da Gaia, i.e. il nome del file ZIP, invece che il nome dei file contenuti al suo interno.
