### ISSUE TITLE
Inserire controllo n.max caratteri nel campo provincia

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#1827]
In fase di registrazione da parte del volontario, nel campo "Provincia di nascita" e "Provincia di residenza" è possibile inserire valori con più di 2 caratteri, invece nella modifica anagrafica lato US prima di salvare una modifica è necessario correggere il campo provincia prima di continuare.

Per replicare errore, andare sull'anagrafica dell'utente id=103036 e cliccare su "Salva modifiche", ci sarà un alert nel campo provincia.

Sarebbe meglio mettere l'alert già in fase di registrazione.

**Comment by ico88** [comment]
@PaoloAgresti in registrazione vi è già tale limitazione, riusciamo a discriminare se è dovuta a registrazione o import in massa ?

**Comment by PaoloAgresti** [comment]
@ico88 è dovuta a registrazione

**Comment by AlfioEmanueleFresta** [comment]
Il controllo viene fatto utilizzando l'attributo `pattern`. Questo viene educatamente ignorato da alcuni browser amorevoli e noti per essere i migliori browser in circolazione. Fallback a `maxlength`.
