### ISSUE TITLE
Presidente Provinciale può approvare fototessera dei Comitati Locali

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#1832]
Un Presidente Provinciale andando nella sezione "Fototessere in attesa" e cliccando su "Dettagli" di un volontario appartenente ad un Comitato Locale, ha la possibilità di Approvare/Negare le fototessere.
Invece in presidente.fototessere.pending ciò non è possibile (giustamente).

**Comment by ico88** [comment]
In che senso ?
Il 23/Gen/2015 09:57 "Paolo" <notifications@github.com> ha scritto:

**Comment by PaoloAgresti** [comment]
Se sono un Presidente Provinciale non posso approvare le foto dei volontari appartenenti ai Comitati Locali del mio territorio.
Invece su GAIA è possibile farlo nella pagina "Fototessere in attesa" cliccando su "Dettagli" di un volontario appartenente ad un CL.
