### ISSUE TITLE
[corsi base] apertura di ?p=formazione.corsibase genera errore fatale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1837]
in modalità admin aprendo la pagina si ottiene errore.

54c3a6b09b7fd29a14b008f2

string(101) "Uncaught 20150124150536 [ERR #1003]: Entità non presente (tabella:id) => 	anagrafica:90803

**Comment by PaoloGiustiniani** [comment]
Risolto.
