### ISSUE TITLE
[beta] autoparco.dash calcolo errato tempi non manutentati

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#1840]
! Attenzione mancata manutenzione.

I seguenti veicoli non vengono manutentati da un anno:
CRI123456 - Ultima manutenzione: 01/04/2001

in realtà non è un anno come da data riportata
veicolo id 544

**Comment by ico88** [comment]
A quando risale ultima manutenzione ?
Il 25/Gen/2015 11:30 "Giovanni" <notifications@github.com> ha scritto:

**Comment by GiovanniLongo** [comment]
come da commento precedente:

CRI123456 - Ultima manutenzione: 01/04/2001

**Comment by ico88** [comment]
Sì é più di un anno é sbagliato solo il testo
Il 25/Gen/2015 12:07 "Giovanni" <notifications@github.com> ha scritto:
