### ISSUE TITLE
accesso di alcuni utenti a gaia genera errore fatale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1842]
l'utente 81285 accedendo a gaia riceve
Rif. errore codice 54c7dfff9b7fd271500334a8
string(94) "Uncaught 20150127195911 [ERR #1003]: Entità non presente (tabella:id) => 	aree:4678

**Comment by matthewmazzoleni** [comment]
stesso errore per utente 5116 al login

54ca33889b7fd2785e9c102c

string(101) "Uncaught 20150129142008 [ERR #1003]: Entità non presente (tabella:id) => 	anagrafica:12461

  thrown"agrafica non presente, problema anche per utente

**Comment by ico88** [comment]
entrambi risolti
