### ISSUE TITLE
comitato vede quota 2015 pagata di un suo ex volontario

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1843]
L'utente 639, Ufficio Soci di un comitato, vede la quota associativa pagata di 2960 per l'anno 2015, nonostante il volontario sia trasferito presso altro Comitato già da metà del 2014

**Comment by matthewmazzoleni** [comment]
sembra il problema sia più ampio, abbiamo anche altre segnalazioni di questo tipo (quote ripetute e conteggiate anche in ex comitati)

**Comment by AlfioEmanueleFresta** [comment]
Questo e' in risoluzione in #1218
