### ISSUE TITLE
Fatal error > static::$_cacheable Entita.php riga 573

### ISSUE THREAD

**Issue by michaelscarabelli** [CroceRossaCatania/gaia#1853]
Rilevato questo errore fatale: Fatal error > static::$_cacheable Entita.php riga 573.

Rilevato mentre testavo l'inserimento di una donazione lato volontario e lato presidente.

Per poter proseguire velocemente con i test sulle funzionalità donazione ho commentato la riga incriminata.

Da debuggare l'errore PHP.

**Comment by ico88** [comment]
Risolto, eventualmente riaprire
