### ISSUE TITLE
[produzione] impossibile selezionare direttore corso base

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#1855]
ticket [XRU-422-91178]
Id: 3098 
Delega: Resp. Formazione

inserendo cognome o nome come screenshot allegato al ticket non compare lista volontari

**Comment by biagiosaitta** [comment]
il problema è che il corso lo hanno attivato nel'unità territoriale di sperlonga (sotto il comitato locale di itri) in cui non hanno inserito nemmeno un volontario quindi il selettore non trova nessuno. Se il direttore del corso è di itri devono fare l'estensione su sperlonga e nominarlo direttore
