### ISSUE TITLE
errore fatale su accesso a pagina presidente.comitato

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1859]
utente: 5116 
errore: 54ca33889b7fd2785e9c102c

string(101) "Uncaught 20150129142008 [ERR #1003]: Entità non presente (tabella:id) => 	anagrafica:12461

**Comment by Potitus** [comment]
metti a fare lavori seri e magari in condivisione

https://github.com/CroceRossaCatania/gaia/issues/1859

ciolone


Il 31/01/2015 16:23, Matthew Mazzoleni ha scritto:

**Comment by AlfioEmanueleFresta** [comment]
@Potitus, scusa?

**Comment by Potitus** [comment]
era un messaggio al mio collega
nel cc c'e anche la mail principale


Il 31/01/2015 16:36, Alfio Emanuele ha scritto:

**Comment by Potitus** [comment]
abbiamo preso visione del problema e siamo interessati a proporre delle 
soluzioni come da vs bug, simile ad un nostro recente lavoro presentato 
ad un noto Comitato elettorale
Il 31/01/2015 16:36, Alfio Emanuele ha scritto:

**Comment by AlfioEmanueleFresta** [comment]
@Potitus grazie per l'interesse. Sentitevi liberi di forkare il progetto, esplorare il codice e proporre patch usando la funzionalità di Pull request su GitHub.

**Comment by ico88** [comment]
Risolto
