### ISSUE TITLE
[produzione] creando attività con referente e chiudendola, referente riceve alert di attività da completare

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#1860]
ticket [RUP-347-39291]

beta:
creata attività, assegnato referente, chiusa attività
referente ad ogni accesso riceve alert di attività da completare

p=attivita.scheda&id=4074
p=profilo.controllo&id=90700

**Comment by ico88** [comment]
La attività prima di essere chiusa era completa ?
Il 01/Feb/2015 15:22 "Giovanni" <notifications@github.com> ha scritto:

**Comment by GiovanniLongo** [comment]
no, ho seguito i passaggi indicati, creata, assegnato referente, chiusa
