### ISSUE TITLE
dimissione non termina deleghe

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1861]
la dimissione di un volontario non termina le deleghe a lui associate, questo rimangono attive fino a forzatura lato presidente della loro conclusione

**Comment by ico88** [comment]
Lato codice non vedo anomalie, riusciamo ad avere più dati ?

**Comment by biagiosaitta** [comment]
simile a questo #1403 bisognerebbe controllare le deleghe al variare dello stato del volontario o al trasferimento in altro comitato

**Comment by ico88** [comment]
Abbiamo provato su beta ?

**Comment by biagiosaitta** [comment]
Sul beta le deleghe del #1403 restano
