### ISSUE TITLE
[dimissioni] errore in fase di operazione

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1865]
54d296079b7fd2297eb60e9a

string(56) "Call to undefined method Volontario::invalidaTesserino()"

MTI-900-58673

Volontario 3480

**Comment by matthewmazzoleni** [comment]
aggiungo caso: su dimissione di 31223 viene generato medesimo errore

**Comment by PaoloGiustiniani** [comment]
nuovo caso UYN-400-35328

**Comment by PaoloGiustiniani** [comment]
E' stato pushato?

Nuovo caso JYB-163-74832

**Comment by PaoloGiustiniani** [comment]
Nuovo caso PSS-337-60415

**Comment by PaoloGiustiniani** [comment]
JZM-247-57752

**Comment by PaoloGiustiniani** [comment]
Lo stesso errore viene generato anche in fase di approvazione trasferimento.

54db64359b7fd2c8498bdc82

**Comment by PaoloGiustiniani** [comment]
54db9b2e9b7fd21f490946fc

anche in caso di conversione da ordinario ad attivo 

I test chi li sta facendo?
