### ISSUE TITLE
[Produzione] Invio email duplicato il bug terrificante è ancora presente

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1866]
Log presenti nel ticket: VEI-318-24622.

Sono pervenute quattro sessioni distinte differenti identificate da quattro lease diversi.

**Comment by matthewmazzoleni** [comment]
se fossero necessari alcuni casi segnalo che la cosa è accaduta ripetutamente per l'utente 6365, anche in data 16 febbraio.
