### ISSUE TITLE
Modifica modalità di iscrizione volontario/aspirante

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1867]
arrivano giornalmente decine di ticket riguardanti la conversione di volontari in aspiranti per errata registrazione. occorre trovare una soluzione che fermi l'iscrizione dell'aspirante sul nascere in caso di errore, in quanto esso entrando in GAIA (spesso rimbalzato da qualche sito CRI) viene attirato dal pulsantone verde "Registrati ora" come per ogni altro sito, non perde tempo a leggere il testo nella pagina, e non si rende conto di registrarsi come Volontario.

è pensabile che dopo la pressione di "registrati ora" venga mostrato come prima schermata un bivio che abbia due "pulsantoni": "Sono già Volontario" e "Voglio diventare Volontario"? se questo può almeno dimezzare i casi sarebbe molto lavoro in meno..

**Comment by biagiosaitta** [comment]
si può mettere un alert dopo aver cliccato il tasto verde registrati ora con scritto "Vai avanti con questa registrazione SOLO SE GIA' SEI UN VOLONTARIO DI CROCE ROSSA altrimenti......"

**Comment by ico88** [comment]
Un modale o roba simile direi

**Comment by FAmeglio** [comment]
otreste anche mettere un tasto solo "registrati" e poi un altert che ti chiede: Sei già volontario? Si, No..

**Comment by AlfioEmanueleFresta** [comment]
E' una cosa molto semplice da fare, se ci fa risparmiare tempo di supporto ben venga. Promossa

**Comment by ico88** [comment]
Esprimete pareri

![schermata del 2015-02-11 20 26 31](https://cloud.githubusercontent.com/assets/3149018/6154472/48b50b78-b22c-11e4-8996-b30b4cde2c20.png)
