### ISSUE TITLE
[importazione massiva] controllo su mail duplicata

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1868]
un comitato, a seguito di import massivo, ha circa 20 utenti con la medesima email. è possibile su duplicato email evitare l'attivazione dell'account (eventualmente segnalandolo nel log?)

**Comment by ico88** [comment]
Se mail già presente non la importo, concordate ?

**Comment by matthewmazzoleni** [comment]
Se aspirante o nel limbo io aggiornerei, che dite? Di fatto poi aprono il ticket per farlo fare noi a mano, tanto vale lo faccia il processo... 

Inviato da iPhone
