### ISSUE TITLE
Nominando nuovo Delegato Obiettivo, competenza Area resta al Presidente

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#1869]
Premesso che rimuovendo un Delegato di Obiettivo Strategico la competenza di tutte le attività di quell'area passano al Presidente, nel momento in cui vado a nominare un nuovo Delegato, la competenza resta del Presidente e non torna al Delegato. 
Ciò è visualizzabile da "Aree di intervento".
Per riprodurre errore (già verificato in beta):
- Rimuovere Delegato Obiettivo;
- Nominare nuovo Delegato Obiettivo;
- Controllare su Aree di intervento il nome del Responsabile.

Ciò non influisce a livello pratico sull'uso di GAIA, ma rappresenta lo stesso un errore.
Rif. [VBI-231-17487]

**Comment by ico88** [comment]
Ciò era una cosa voluta sinceramente

**Comment by PaoloAgresti** [comment]
Ma poi nominando il nuovo Delegato, le attività non dovrebbero tornare in capo a lui??
