### ISSUE TITLE
Membro trasferito e/o dimesso viene mostrato sia nel vecchio che nel nuovo comitato

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1872]
Nonostante la data sia passata abbiamo questa casistica.

Ad esempio. volontario 22433 

FSA-691-11552

**Comment by PaoloGiustiniani** [comment]
Nuovo caso 104517 & 80927

Membro dimesso come attivo ed ora ordinario.

**Comment by ico88** [comment]
Parliamo che viene visto nell'elenco soci o nei dettagli del volontario ?
