### ISSUE TITLE
[tesserini] non viene mostrato pulsante di richiesta tesserino

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1876]
l'utente 6928, utente con ruolo US, non visualizza alcuni pulsanti di richiesta tesserino per Volontari aventi fototessera caricata da US stesso. un Volontario (tra tanti) per cui non è mostrato il pulsante è 22043.

**Comment by PaoloGiustiniani** [comment]
Altro caso YPW-933-14759

**Comment by ico88** [comment]
Mi fate i test chiesti ? Grazie

**Comment by matthewmazzoleni** [comment]
gli utenti indicano che ancora non viene mostrato il pulsante di richiesta tesserino

**Comment by PaoloGiustiniani** [comment]
Altro caso

YXG-519-76040

**Comment by AlfioEmanueleFresta** [comment]
Veniva fatto un controllo errato, non compariva il pulsante per quei volontari in una **unita' territoriale** senza posizione (indirizzo inserito). Invece il controllo viene ora fatto sul livello di comitato **locale**.
