### ISSUE TITLE
Impossibile rimuovere spunta IIVV o CM

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#1878]
US segnala che, una volta attribuita, non è possibile rimuovere la spunta Corpo Militare.
Verificato in beta anche per IIVV.

rif. ticket FMG-882-33249

**Comment by ico88** [comment]
Gli admin possono, @PaoloGiustiniani ha senso dare a loro anche questo potere ?

**Comment by PaoloGiustiniani** [comment]
Direi di sì, è una modifica irrilevante.
