### ISSUE TITLE
[elenchi] errore fatale in generazione elenco soci

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1879]
9934 ottiene 54d902369b7fd20812e304b0 su generazione elenco soci.

string(50) "Call to a member function format() on a non-object"

**Comment by ico88** [comment]
Su generazione elenco soci o excel ?

**Comment by matthewmazzoleni** [comment]
@ico88 chiedendo all'utente confermo su scaricamento.

succede anche qui: string(50) "Call to a member function format() on a non-object"
per utente 2625

**Comment by matthewmazzoleni** [comment]
aggiunto: 81410 medesimo errore
