### ISSUE TITLE
[attività] apertura dettaglio genera errore fatale per 4847 

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1880]
su apertura del dettaglio attività con id 4852 l'utente 4847 ottiene errore 54d8f26f9b7fd2246ae10cfb

string(109) "Uncaught 20150209184623 [ERR #1000]: Errore non documentato - fare riferimento al supporto tecnico"

**Comment by AlfioEmanueleFresta** [comment]
Non saro' mai orgoglioso di me stesso abbastanza per aver scritto quel messaggio di errore cosi' bene. Ti da l'impressione che forse, al mondo, qualcuno ha la minima idea di cosa voglia dire. Da indagare.

**Comment by ico88** [comment]
Non riesco a capire dove sta l'errore

**Comment by matthewmazzoleni** [comment]
ove mai servisse: 54eb28349b7fd21f7c49065f
 Errore non documentato - fare riferimento al supporto tecnico"
TAM-118-51291
