### ISSUE TITLE
[quote] generazione elenco genera errore fatale per utente 9934

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1881]
la generazione dell'elenco quote non pagate genera 54d940919b7fd25d5cabbb94

string(50) "Call to a member function format() on a non-object"

verificato. ETR-367-88449

**Comment by ico88** [comment]
Dobbiamo fare lo stesso lavoro fatto per soci se data non valida compare
errore ma genera comunque
Il 10/Feb/2015 00:30 "Matthew Mazzoleni" <notifications@github.com> ha
scritto:

**Comment by matthewmazzoleni** [comment]
aggiungo ZSF-282-44459
