### ISSUE TITLE
[attività] entità non presente in elenco attività chiuse

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1884]
54da61d59b7fd2fa64d79c06

string(94) "Uncaught 20150210205357 [ERR #1003]: Entità non presente (tabella:id) => 	aree:3568 thrown"

**Comment by PaoloGiustiniani** [comment]
altro caso

54d9f6259b7fd27b70df905f

string(94) "Uncaught 20150210131429 [ERR #1003]: Entità non presente (tabella:id) => 	aree:4678  thrown"

**Comment by ico88** [comment]
fixato
