### ISSUE TITLE
[attività] errore in fase di creazione

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1888]
L'utente 43760 ci segnala che in fase di salvataggio dell'attività ottiene il seguente messaggio di errore

54db9ce19b7fd2214adee143

string(56) "Call to a member function nomeCompleto() on a non-object"

SDV-204-68729

**Comment by matthewmazzoleni** [comment]
inserendo un'attività: 54faa8099b7fd2b10d05899b
string(109) "Uncaught 20150307082601 [ERR #1000]: Errore non documentato - fare riferimento al supporto tecnico	

  thrown"

riscontrata da 6606

**Comment by AlfioEmanueleFresta** [comment]
Guardando caso e codice, molto probabilmente era dovuto ad una corruzione in DB. Considero corretto fino a prova contraria. @PaoloGiustiniani puoi chiedere all'utente se ora funziona, ed eventualmente riaprire per favore.

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni sfortunatamente non riesco a riprodurre con 6006. Potrebbe essersi risolto?
