### ISSUE TITLE
[dimissioni] aggiunta motivazioni

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1892]
- perdita requisiti previsti per l'accesso o la permanenza
- sospensione ingiustificata dal servizio attivo per un periodo superiore ai due mesi solari

**Comment by ico88** [comment]
Da aggiungere alle attuali ? 
Attualmente sono:
- Dimissioni Volontarie;
- Mancato svolgimento turno;
- Mancato rientro da riserva;
- Mancato versamente quota annuale;
- Radiazione da Croce Rossa Italiana;
- Decesso.

**Comment by biagiosaitta** [comment]
La seconda di sopra mi sembra uguale alla seconda di sotto! La perdita dei requisiti la aggiungerei
