### ISSUE TITLE
[trasferimenti] errore su approvazione del presidente

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1897]
abbiamo segnalazioni in cui si indica che, a fronte di un Volontario che chiede il trasferimento, se il Presidente del Comitato uscente approva il trasferimento la procedura va in errore.

esempio di volontario in fase di trasferimento: 63456

aggiungo: dopo il tentativo di approvazione da parte del Presidente uscente il trasferimento è segnalato al Comitato di destinazione nei contatori "trasferimenti in attesa" ma non viene mostrato alcun trasferimento una volta acceduto all'elenco

ticket con i dettagli specifici: ZP-834-34677

**Comment by ico88** [comment]
@matthewmazzoleni con https://github.com/CroceRossaCatania/gaia/commit/d957c0e46faef974460211aab0de4aa7b3ba4904 verificare se risolto
