### ISSUE TITLE
[quote] Modificare ricevuta emessa da GAIA

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1903]
1)Nel PDF della ricevuta emessa da GAIA dovrà essere rimossa/oscurata la seguente voce:
"Quota registrata da: XXX"
2)Nelle pagine us.quoteSi / us.quoteSiordinari dovrà essere aggiunta una nuova colonna che riporterà, solo ad ufficio soci / presidente, chi ha effettivamente registrato la quota.

**Comment by livodario** [comment]
Ciao, nel PDF della ricevuta, nella zona riservata alle info di comitato (in basso a destra), il campo telefono viene mostrato come:
Tel.: _TEL
mentre indirizzo, cf e p.iva sono visualizzati correttamente.
Il campo telefono è stato correttamente settato dal Presidente di comitato.

**Comment by PaoloGiustiniani** [comment]
Ciao @livodario,
potresti inviare queste tipologie di segnalazioni a mezzo ticket?

La issue in questione è riferita ad un brach di progetto.

Grazie.

**Comment by livodario** [comment]
Ok, scusate, provvedo subito!
Grazie!
