### ISSUE TITLE
[trasferimenti] Bloccati nonostante protocollo e autorizzazione

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1910]
I trasferimenti risultano attualmente bloccati nello stato "Trasferimento in corso" nonostante la richiesta sia stata protocollata ed autorizzata.

Esempi
presidente.appartenenze.storico&id=62573
presidente.appartenenze.storico&id=35180 

QNQ-279-53035
DLO-412-75917

**Comment by PaoloGiustiniani** [comment]
Altri casi
presidente.appartenenze.storico&id=22778
presidente.appartenenze.storico&id=24153 

XZI-244-51352
VZR-947-38087

**Comment by PaoloAgresti** [comment]
Altro caso 
IPJ-116-70856

**Comment by ico88** [comment]
Per i precedenti vanno ripassati in presidente.trasferimento.ok&si&id=idtrasferimento

**Comment by PaoloGiustiniani** [comment]
@ico88 pur processando a mano il trasferimento "2051" lo stato rimane invariato.

Puoi verificare?

**Comment by matthewmazzoleni** [comment]
up

**Comment by AlfioEmanueleFresta** [comment]
@ico88 sai qual e' il problema? Altrimenti assegnami

**Comment by matthewmazzoleni** [comment]
aggiungo casi:
?p=presidente.utente.visualizza&id=102784
?p=presidente.utente.visualizza&id=102790

**Comment by matthewmazzoleni** [comment]
up

**Comment by matthewmazzoleni** [comment]
up
