### ISSUE TITLE
[pdf] richiesta estensione KO

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1911]
string(69) "/home/gaia/public_html/gaia/inc/utente.estensioneRichiesta.stampa.php"

string(50) "Call to a member function format() on a non-object"

Richiesta 3293

XXM-832-56287

**Comment by ico88** [comment]
Verificate db, vi é un problema nella data

**Comment by AlfioEmanueleFresta** [comment]
Dati corrotti. Sistemare casi individuali quando occorre. Non riproducibile.
