### ISSUE TITLE
[storico turni] Reindirizza a "utente.me"

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1912]
Aprendo la pagina dello storico turni di un volontario si viene re-indirizzati alla pagina "utente.me"

La problematica non si verifica con privilegi di admin ma solo con privilegi da utente.

Potete provare con l'ID 4901.

**Comment by ico88** [comment]
Aprendo come US ?

**Comment by PaoloGiustiniani** [comment]
Sì. 

Ma va fatto login con l'utente indicato.

**Comment by PaoloGiustiniani** [comment]
La casistica di verifica come US e non come presidente.
