### ISSUE TITLE
[autoparco] autoparco del Comitato Provinciale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1913]
l'utente 3004 non riesce (da delegato autoparco del CP) a creare un autoparco Provinciale. Ho verificato e il Volontario è delegato all'autoparco Provinciale e a quello del CP fake, ma di fatto può creare solo Autoparchi legati al CP Fake.

SEJ-394-12869

**Comment by ico88** [comment]
Ha la delega corretta selezionata ?

**Comment by AlfioEmanueleFresta** [comment]
Il sistema attuale permette la creazione di autoparchi solo sul livello di unita' territoriale.
