### ISSUE TITLE
Email reminder dell'inizio attività a soci confermati

### ISSUE THREAD

**Issue by giordanotrecca** [CroceRossaCatania/gaia#1927]
Ciao,
ormai oggi quasi tutti hanno uno smartphone e sarebbe utile che un cronjob controlli periodicamente le attività che devono iniziare e, X ore prima o il giorno prima, invii in automatico una email (unico sistema facile e gratuito) a tutti i soci che sono stati confermati per l'attività in modo da ricordargli l'impegno.

Ovviamente questo sistema non raggiungerà tutti in modo immediato ma, in attesa di vincere al superenalotto e comprare un server SMS... piutòst che nient, l'è mej piutòst ;-)
Ciao e buon lavoro!

**Comment by PaoloGiustiniani** [comment]
Ciao Giordano,
ti chiediamo si inviare i feedback tramite e-mail all'indirizzo feeeback@gaia.cri.it.

Valuteremo periodicamente lo sviluppo di nuove funzionalità.

Grazie.

**Comment by giordanotrecca** [comment]
ops... troppo tardi... ne ho già mandato un altro... la prox volta vedrò di fare come chiedi. Scusate :-)
Ciao e buon lavoro!
