### ISSUE TITLE
Ruoli del personale su Attività

### ISSUE THREAD

**Issue by giordanotrecca** [CroceRossaCatania/gaia#1928]
Ciao,
un'altra proposta:
l'uso ormai quotidiano della gestione attività ci ha mostrato l'esigenza di poter impostare in ogni singolo turno anche i RUOLI delle figure richieste per il turno.

Ciao e buon lavoro!

**Comment by AlfioEmanueleFresta** [comment]
Ciao @giordanotrecca, potresti scrivere a feedback@gaia.cri.it cosa intendi per ruolo delle figure richieste?

**Comment by giordanotrecca** [comment]
Ciao,
per "ruoli" si intende la qualifica richiesta al volontario che si richiede
nel turno di servizio.

Quando saranno definite le qualifiche si potrebbero utilizzare dei filtri
su qualifiche confermate dei soci... (in futuro)...

Per ora potrebbero bastare anche delle voci "libere" che ogni coordinatore
di attività si gestirà in autonomia.
In prativa invece di segnare "da X a Y volontari" poter segnare ogni
tipologia necessaria al servizio.

Esempio:
- 2 autista cat.5
- 2 soccorritore PS operatore DAE
- 4 soccorritore
- 1 coordinatore primo livello
- 1 tecnico TLC
- ecc...

Spero di essermi spiegato ;-)
Ciao e buon lavoro
Giordano

2015-02-27 4:04 GMT+01:00 Alfio Emanuele <notifications@github.com>:

**Comment by AlfioEmanueleFresta** [comment]
@giordanotrecca per favore scrivi a feedback@gaia.cri.it, non qui.

**Comment by AlfioEmanueleFresta** [comment]
Perdona, ho visto solo ora che avevi messo feedback in copia, non appare su github. Grazie.
