### ISSUE TITLE
[quote] Sul PDF non compare numero della ricevuta

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#1930]
Sul PDF della ricevuta di pagamento non compare il numero della ricevuta.

https://gaia.cri.it/index.php?p=us.quote.ricevuta&id=58466

**Comment by AlfioEmanueleFresta** [comment]
Ieri ho integrato le modifiche al sistema di quote. Le quote sono state rinumerate correttamente circa mezz'ora fa.
