### ISSUE TITLE
[tesserini] non appare pulsante di richiesta per alcuni volontari

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1935]
per alcuni volontari non apparte il bottone azzurro di richiesta tesserino:
esempi: 52957, 106793, 52950, 116996, 

l'utente che riscontra il problema è 29878 con ruolo US

**Comment by AlfioEmanueleFresta** [comment]
I tesserini appaiono tutti richiesti ad oggi. Chiudo.
