### ISSUE TITLE
[autoparco] allocazione veicolo genera errore

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1936]
il presidente 9715 su operazione in oggetto ottiene:
54fa36b79b7fd2e461d73c59
string(56) "Call to a member function getTimestamp() on a non-object"
string(64) "/home/gaia/public_html/gaia/inc/autoparco.veicolo.colloca.ok.php"

**Comment by ico88** [comment]
Testato funziona correttamente, il problema sta nel non corretto utilizzo del calendario.
Penso proprio che l'utente inserisce manualmente solo la data senza orario il che genera l'errore sopracitato.
