### ISSUE TITLE
[autoparco] excel dei rifornimenti vuoto

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1938]
Un utente ci segnala che l'excel generato dalla pagina "autoparco.veicolo.rifornimenti&id=596" ---> "autoparco.veicolo.rifornimenti.excel&id=596" nonostante su Gaia siano presenti dei dati viene generato vuoto.

Bug verificato

NTE-638-66004

**Comment by ico88** [comment]
Singolo caso o accade per tutti ?

**Comment by ico88** [comment]
up

**Comment by PaoloGiustiniani** [comment]
Per ora lo segnala quell'utente, ed il file generato è vuoto.
