### ISSUE TITLE
[excel] zip volontari giovani genera errore

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1940]
5502070b9b7fd28c61857ceb string(50) "Call to a member function format() on a non-object"

**Comment by matthewmazzoleni** [comment]
anche a utente 12569 viene generato 5501bf729b7fd28215bb2c75 "Call to a member function format() on a non-object"

**Comment by matthewmazzoleni** [comment]
up

**Comment by AlfioEmanueleFresta** [comment]
Risolto.
