### ISSUE TITLE
[rubrica] visualizzazione fototessera

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1944]
elenco le richieste ad oggi pervenute:

- nella visualizzazione della Rubrica dei volontari chiedo avvenga per default la visualizzazione della foto del tesserino e non quella di avatar, per questi semplici motivi:
 quando si cerca un volontario dovrebbe apparire il suo viso che poi è quello della tessera e non altre foto di libero arbitrio pubblicate.
 ieri ho caricato un centinaio di fototessere che avevo già. ora dovrei visualizzare quelle mancanti (ciò si può vedere in altro modo solo accedendo ai dati del singolo volontario)
 
anche visualizzando i dati del volontario appare di default la foto avatar, invece dovrebbe apparire a mio giudizio, come default  la foto della tessera.

**Comment by PaoloAgresti** [comment]
concordo

**Comment by GiovanniLongo** [comment]
idem... anzi l'avatar si potrebbe anche togliere, non so se ha senso che esista...
