### ISSUE TITLE
[volontarizza] errore di permessi per presidente o us

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#1945]
Vi sono dei problemi con la fuzione in oggetto (presidente.utente.volontarizza).

Una volta premuto il tasto viene mostrato un errore di permessi.

Es: JXW-197-92981

**Comment by ico88** [comment]
Con che ruolo ?

**Comment by PaoloGiustiniani** [comment]
Presidente e us.

**Comment by matthewmazzoleni** [comment]
up

**Comment by ico88** [comment]
Livello del presidente, ho provato con presidente locale volontarizzazione di ordinario e funziona

**Comment by matthewmazzoleni** [comment]
prova sui provinciali fake (prova un US e un P) es: JXW-197-92981
