### ISSUE TITLE
Email di conferma trasferimento viene inviata al Presidente

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#1946]
La mail di conferma del trasferimento viene inviata erroneamente al Presidente del Comitato.

Il testo della mail è:
"Ciao [nome volontario], buone notizie.

La tua richiesta di trasferimento presso il Comitato Provinciale Di Treviso: Treviso inoltrata il 11/03/2015 è stata approvata.

Se pensi che ci sia stato un errore, ti invitiamo a rispondere a questa email indicandoci cosa c'è da correggere."

**Comment by AlfioEmanueleFresta** [comment]
@PaoloAgresti puoi confermarmi che si tratta di una conferma automatica allo scadere dei 30 giorni?

**Comment by AlfioEmanueleFresta** [comment]
Il problema risiede in https://github.com/CroceRossaCatania/gaia/blame/master/core/class/Trasferimento.php#L77

**Comment by PaoloAgresti** [comment]
Parliamo di una riserva confermata inserendo n. Protocollo.

**Comment by ico88** [comment]
Sembrerebbe funzionare ci sono tutti i destinatari https://github.com/CroceRossaCatania/gaia/blob/master/core/class/Trasferimento.php#L215
