### ISSUE TITLE
[tesserini] non viene mostrato pulsante di generazione ed emissione a US regionale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1952]
a fronte di un tesserino richiesto da un CL il CR (provato con delegato US) non visiona a fianco del socio il pulsante di generazione/emissione del tesserino. provato con utente 2054 (ruolo US di CR).

**Comment by matthewmazzoleni** [comment]
up

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni riesco correttamente a completare la procedura da https://gaia.cri.it/?p=us.tesserini.
