### ISSUE TITLE
[estensioni] errore su richiesta termine estensione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1953]
il Presidente 5116  su azione di terminazione estensione per 16976 riceve:

550d870a9b7fd23b5a360aca

string(117) "Uncaught 20150321155818 [ERR #1018]: Email impossibile da inviare: nessun destinatario con indirizzo email	

  thrown"

**Comment by ico88** [comment]
L'estensione risulta terminata correttamente, il problema è insito nel sistema di invio email che ove non trova un indirizzo fallisce e non ignora @AlfioEmanueleFresta
