### ISSUE TITLE
[attività] errore su salvataggio turno

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1954]
utente 3599  su salvataggio di un turno riceve
550c2d319b7fd2525d6e2b93

string(109) "Uncaught 20150320152241 [ERR #1000]: Errore non documentato - fare riferimento al supporto tecnico	

  thrown"

**Comment by AlfioEmanueleFresta** [comment]
Sfortunatamente non riesco a indagare o riprodurre senza ulteriori informazioni. Se capita nuovamente, sentiti libero di riaprire l'issue.
