### ISSUE TITLE
[trasferimenti] Trasferimento rimane nel "limbo"

### ISSUE THREAD

**Issue by biagiosaitta** [CroceRossaCatania/gaia#1960]
Ci sono dei trasferimenti in corso (da più di un mese, quindi dovevano essere approavati d'ufficio) che sono in una sorta di limbo, ovvero non li fa confermare anche se sono protocollati (volontari id 236 e 70223)

**Comment by ico88** [comment]
LA problematica sembra risolta, ho controllato gli id e sembra tutto ok
