### ISSUE TITLE
[trasferimenti] Errore conferma trasferimenti

### ISSUE THREAD

**Issue by biagiosaitta** [CroceRossaCatania/gaia#1961]
Quando si conferma un trasferimento viene restituito il seguente errore:
Fatal error: Call to a member function comitato() on a non-object in gaia/inc/presidente.trasferimento.ok.php on line 6

**Comment by AlfioEmanueleFresta** [comment]
@biagiosaitta ho bisogno di sapere se l'errore si manifesta in queste condizioni:

* Senza selezionare alcuna delega dal selettore di sinistra
* Avendo selezionato una delega dal selettore di sinistra
