### ISSUE TITLE
[aspiranti] verifica modalità cancellazione dati

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1963]
eliminando alcune anagrafiche è successo che non fossero correttamente gestite le cancellazioni delle preiscrizioni/iscrizioni a corsi base o eventuali associazioni a presenze, assenze, etc..

sarebbe opportuno che il metodo di eliminazione di anagrafiche verifichi anche la presenza di relazioni in tali tabelle.

**Comment by matthewmazzoleni** [comment]
up

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni te lo risolvo rapidamente appena posso

**Comment by matthewmazzoleni** [comment]
già che ci sei controlla che oltre a preiscrizioni e iscrizioni non manchi altro :) thanks @AlfioEmanueleFresta

**Comment by matthewmazzoleni** [comment]
up
