### ISSUE TITLE
[refuso] correzione pagina estensioni

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1964]
refuso nelle terminologie utilizzate nella pagina:
![immagine](https://cloud.githubusercontent.com/assets/5826472/6872156/9835337e-d4a7-11e4-9109-6191c37dcb59.png)

**Comment by AlfioEmanueleFresta** [comment]
Corretto da @PaoloGiustiniani con 5ffc70b5cdb1524f86ca479b5302cfec39914851.
