### ISSUE TITLE
[elenchi] elenco elettorato non considera appartenenze passate

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1970]
la generazione elenco elettorato sembra non tenere conto di appartenenze passate, quindi calcola l'anzianità solamente sull'appartenenza attuale

**Comment by matthewmazzoleni** [comment]
aumentano le segnalazioni

**Comment by AlfioEmanueleFresta** [comment]
Non mi risulta sia piu' il caso, secondo il codice che leggo. Chiudo.

**Comment by matthewmazzoleni** [comment]
ti porto l'exempio di 15776, 53431 e 53467 che non compaiono nella lista elettorale, che trovi in allegato (excel) nel ticket EXC-143-98880

**Comment by PaoloGiustiniani** [comment]
L'utente segnala che il problema in questione non è stato risolto VZE-423-40390

**Comment by matthewmazzoleni** [comment]
un altro utente EXC-143-98880 segnala il problema medesimo (elettorato valuta anzianità solamente da attuale appartenenze, senza considerare il pre-trasferimento).
