### ISSUE TITLE
[quote] problematiche varie

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1971]
Sono qui elencate le problematiche legate alle quote:

**Comment by matthewmazzoleni** [comment]
- volontario trasferito viene mostrato nell'ex comitato come non pagante
- persone risultano sia nelle quote degli attivi che in quelle degli ordinari
- volontario che paga quota in comitato nuovo, a seguito di trasferimento, viene mostrato nelle quote pagate dell'ex comitato.

**Comment by matthewmazzoleni** [comment]
up

**Comment by AlfioEmanueleFresta** [comment]
Buona parte di queste dovrebbero essere state causate da incongruenze nel database. Dovrebbero quindi ora essere state risolte. Se non lo sono, per favore segnalatemelo nuovamente.

**Comment by matthewmazzoleni** [comment]
aumentano segnalazioni

**Comment by PaoloGiustiniani** [comment]
aumentano segnalazioni

**Comment by PaoloGiustiniani** [comment]
aumentano segnalazioni.

**Comment by PaoloGiustiniani** [comment]
aumentano segnalazioni

**Comment by PaoloGiustiniani** [comment]
aumentano segnalazioni.
