### ISSUE TITLE
[mappa] email errate su ?p=public.comitati.mappa

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1972]
sulla pagina con la mappa dei comitati sono presenti email errate per i CR (ad esempio Lombardia e Basilicata) che sembrano mostrare indirizzi di loro Comitati invece delle loro.

**Comment by ico88** [comment]
@matthewmazzoleni non mi risulta il problema

**Comment by delbe87** [comment]
Scusate se riapro, ma per esempio, il CR Valle d'Aosta se cliccato nella mappa, i dettagli che si aprono visualizzano la mail del cp.palermo e non cr.valledaosta mentre il CR Lombardia mostra la mail cp.savona

**Comment by PaoloGiustiniani** [comment]
Ciao @delbe87 puoi svuotare cache e cookie e riprovare?

**Comment by AlfioEmanueleFresta** [comment]
Il problema segnalato da @matthewmazzoleni e @delbe87 si verificava solamente con gli indirizzi e-mail dei comitati regionali (il resto dei livelli e dati erano corretti). Corretto.
