### ISSUE TITLE
[turni] errore durante l'eliminazione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1973]
18081 mentre eliminava turni ha ottenuto 55197fdf9b7fd2614cc65f9d
string(56) "Call to a member function getTimestamp() on a non-object"

**Comment by matthewmazzoleni** [comment]
up

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni molto probabilmente quello che accade e' che l'utente, prima di premere il tasto "Cancella", svuoti i campi (incluso quello della data), generando l'errore in questione. Questo non e' necessario. L'errore non e' altresi' riproducibile e non richiede fix.
