### ISSUE TITLE
[browser] problemi con l'utilizzo di IE11

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1978]
molti utenti segnalano problemi con IE11 (browser obsoleto, menù con problemi di funzionamento, problemi negli editor).

eventualmente da valutare l'uso di 
<meta http-equiv="X-UA-Compatible" content="IE=10">
e la corretta gestione della versione nel check dei browser

**Comment by AlfioEmanueleFresta** [comment]
IE 11 ha una grossa fetta di mercato al momento, purtroppo. Bisogna considerare l'opzione di usare dei polyfill per le funzionalita' mancanti, che ne dite?

**Comment by ico88** [comment]
Concordo
