### ISSUE TITLE
[elenco soci] generazione non tiene conto di diverso stato

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1979]
la generazione dell'elenco soci ad una data non tiene conto dello stato della persona a quella data.
esempi:

- soci attualmente attivi che a quella data erano ordinari vengono estratti come attivi.
- soci dimessi nel 2015 per decesso non figurano nell'elenco soci al 31/12/2014

**Comment by matthewmazzoleni** [comment]
up.

**Comment by ico88** [comment]
Scusa per il punto uno elenco soci ha gli ordinari anche, perchè dovrebbe essere un problema ?

Mi dai un id di un decesso ?

**Comment by matthewmazzoleni** [comment]
per il punto primo: verifico con l'utente.

per il decesso: non posso in quanto appunto gli utenti dimessi per questo motivo non sono più richiamabili in GAIA (trovi però le info qui: UPK-890-93071
