### ISSUE TITLE
[deleghe] alcune deleghe rimangono in essere anche se terminate

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1980]
sono segnalati casi in cui la delega viene cessata ma continua a rimanere il permesso per il Volontario di operare con quella delega.

segnalato al momento per US, Autoparco e DTL/DTP

dettagli qui: WGX-199-74636

**Comment by matthewmazzoleni** [comment]
aumentano richieste

**Comment by ico88** [comment]
Il problema persiste ?
Non trovo nel codice nulla che non vada

**Comment by AlfioEmanueleFresta** [comment]
Il caso riguarda la mancata notifica del termine della delega, che attualmente non e' prevista, piuttosto che la effettiva mancata cessazione in essere della delega. Chiudo.
