### ISSUE TITLE
[email di massa] problema link

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1983]
i link inseriti nelle email di massa arrivano mancanti della parte iniziale dell'url:

nell'esempio qui sotto, inviato da un utente, si vede come la parte di testo visibile nel tag href sia mancante della parte iniziale.
<p><a href="?p=attivita.scheda&amp;id=5526">https://gaia.cri.it/?p=attivita.scheda&amp;id=5526</a></p>

**Comment by ico88** [comment]
@matthewmazzoleni quale email ? tutte ?

**Comment by AlfioEmanueleFresta** [comment]
Riguarda una impostazione dell'editor WYSIWYG, che relativizza tutti gli URL al path attuale. Vedi http://www.tinymce.com/wiki.php/Configuration:relative_urls
