### ISSUE TITLE
[quote] ricevute mostrano differenze

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1985]
incollo casistica segnalata dall'utente: nei due casi (iscrizione e rinnovo) vengono mostrate due ricevute differenti.

![image](https://cloud.githubusercontent.com/assets/5826472/6994748/d7438f38-db24-11e4-81e4-55ae3b4849a3.png)

**Comment by matthewmazzoleni** [comment]
up

**Comment by dan-it** [comment]
Nel file  gaia/inc/us.quote.nuova.ok.php c'è un errore di battitura in linea 155. "offeta" invece che "offerta"

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta sulle quote già emesse dovrebbe avere effetto in caso esse vengano rigenerate? perché risulta ancora così la situazione in questi casi YFR-794-44438

**Comment by matthewmazzoleni** [comment]
segnalano in ERC-722-45176 che ora la cifra eccedente la quota non viene indicata come offerta/oblazione ma solo riportata nella ricevuta senza descrizione alcuna. è voluto?
