### ISSUE TITLE
[turni] impossibile cancellare "Turno 1"

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#1999]
creando un'attività, e andando a creare il primo turno di essa, se interrompo la procedura non è più possibile eliminare tale "Turno 1" che però rimane aperto nel calendario.

**Comment by ico88** [comment]
@matthewmazzoleni è possibile comunque modificarlo ?

**Comment by delbe87** [comment]
Si si può modificare ma non cancellare. Se si prova a cancellare un unico turno futuro al momento del salvataggio viene generato un turni "Turno 1" nella data ed orario del salvataggio

**Comment by ico88** [comment]
@delbe87 non ne vedo la problematica, se l'attività non serve la cancello, se serve almeno un turno ci dovrà essere

**Comment by delbe87** [comment]
questo era sorto in un ticket di supporto che un referente aveva erroneamente inserito un turno, ancora prima di sapere esattamente le date dei vari turni dell'attività. ha cancellato tutti i turni ma uno è rimasto e dei volontari "istantaneamente" si erano iscritti al turno e lui chiedeva come mai non si cancella. MA credo si possa lasciare così. succederà rare volte

**Comment by ico88** [comment]
oook chiudiamo
