### ISSUE TITLE
[soci/sostenitori] adeguamento gaia

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2000]
è necessario adeguare GAIA per la gestione delle nuove figure previste.

**Comment by ico88** [comment]
@matthewmazzoleni ovvero ?

**Comment by delbe87** [comment]
Negli statuti dei CL e CP sono presenti i Volontari ed i Sostenitori (ex Soci Ordinari) e sono stati abrogati i Soci Ordinari che però rimangono nello statuto dei Comitati Regionali e Nazionale.
Sarebbe da adeguare così: i CL ed i CP (sino a quando ci saranno) dovrebbero visualizzare e gestire i Volontari come ad oggi ed i Sostenitori (come gestiscono oggi i Soci Ordinari), mentre gli ordinari dovrebbero rimanere in gestione e visualizzazione ai soli CR e CC

**Comment by ico88** [comment]
ah ok

**Comment by PaoloGiustiniani** [comment]
@ico88 ti sto inviando ordinanza completa via email.

**Comment by ico88** [comment]
@PaoloGiustiniani girala a tutti

**Comment by PaoloGiustiniani** [comment]
@CroceRossaCatania/sviluppatori http://www.cri.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/26091
