### ISSUE TITLE
[trasferimento massivo] implementazione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2001]
necessitiamo di un processo che accetti un csv con colonne:

- CF
- Comitato di Destinazione
- Data di trasferimento
- Motivazione

su conferma si avvii il processo di trasferimento, approvando contestualmente lo stesso verso il comitato di destinazione (la useremo per trasferimenti già certificati su cartaceo, quindi già approvati).

**Comment by matthewmazzoleni** [comment]
up aumentano richieste

**Comment by matthewmazzoleni** [comment]
aumentano richieste di spostamenti massivi per revisione delle strutture del comitati

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni Si puo' fare con un CSV per Comitato di Destinazione? (ie. selezione comitato tramite selettore di Gaia contestuale al caricamento del file e non tramite lo stesso CSV)

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta se intendi che ti passo tutti i campi che ho elencato, senza il "Comitato di Destinazione" che prendo da un selettore per me no problem
