### ISSUE TITLE
[soci] socio attivo con 28 euro di quota non considerato sostenitore

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2007]
come da oggetto: 13005 non risulta sostenitore anche a fronte del versamento di 28 euro.

comitato non presenta quota elevata, lo status è correttamente impostato a Volontario.

**Comment by ico88** [comment]
@matthewmazzoleni che quota ha inserito il comitato ?

**Comment by matthewmazzoleni** [comment]
@ico88 è scritto.

**Comment by AlfioEmanueleFresta** [comment]
La Quota aggiuntiva per i soci benemeriti è stata impostata erroneamente dal Presidente a 28,00 euro, andando a sovrascrivere la quota di default di 20,00 euro. Questo vuol dire che per il Comitato di Cuneo, l'importo minimo per la benemerenza è salita a 36,00 per il 2015.
