### ISSUE TITLE
Campi obbligatori in Anagrafica volontario

### ISSUE THREAD

**Issue by PaoloAgresti** [CroceRossaCatania/gaia#2010]
Nell'inserimento di un nuovo volontario alcuni campi vengono indicati come obbligatori e altri come facoltativi.
Invece nella scheda anagrafica del volontario sono tutti obbligatori.
Se US vuole effettuare una modifica dei dati anagrafici del volontario, per poter salvare le modifiche, è obbligato ad inserire tutti i dati (che magari in quel momento non ha), dovendo quindi inserire dati fittizzi.

Propongo di eliminare l' "obbligatorietà" dei campi anche dalla scheda anagrafica dei volontari.

**Comment by ico88** [comment]
@PaoloAgresti specifichiamo di quali campi parliamo

**Comment by ico88** [comment]
@PaoloAgresti puoi specificare ?
