### ISSUE TITLE
[attività] problemi su autorizzazioni

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2011]
referente di attività segnala che a fronte di 15 richieste di autorizzazione, da lui approvate, gli viene segnalato che 9 sono approvate mentre 6 sospese.

allega screenshots e ulteriori dettagli in DLK-544-26458

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni @delbe87 ho controllato DLK-544-26458. L'attivita' e' stata creata presso l'unita' territoriale di Napoli. I volontari rimasti in sospeso hanno appartenenze presso altri territoriali. Per questo motivo, la generazione delle autorizzazioni ha creato due richieste, una per il referente dell'attivita' che ha aperto il ticket ed un'altra per il presidente di Napoli, rimasta in sospeso. 

Per favore informate l'utente. Chiudo.
