### ISSUE TITLE
[iivv] importazione automatica genera anomalia di visibilità

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2014]
importanto delle IIVV con apposito campo ultimo valorizzato si genera questo caso strano:

esse non sono visibili nell'elenco delle IIVV da US fino a quando non si entra nel loro profilo e si preme "salva", anche senza modificare alcunché.

esempio: 139789 non è presente nella lista IIVV ma il profilo sembra corretto

**Comment by ico88** [comment]
Va effettuato n eventuale aggiornamento del db per corregge le precedent

**Comment by AlfioEmanueleFresta** [comment]
@ico88 hai fatto tu l'aggiornamento del Database? Non trovo dati con True

**Comment by ico88** [comment]
Devi cercare 1

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta e @ico88 posso ritenere chiuso l'issue?

**Comment by ico88** [comment]
Si ripresenta ?
Il 02/mag/2015 01:47, "Matthew Mazzoleni" <notifications@github.com> ha
scritto:

**Comment by matthewmazzoleni** [comment]
@ico88 se la bonifica è stata fatta anche sul pregresso io comunico all'utente la risoluzione, in caso contrario non posso indicargli la risoluzione del problema

**Comment by AlfioEmanueleFresta** [comment]
Confermo.
