### ISSUE TITLE
[presidente.utenti.dimessi] stampa pdf con link riammissione 

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#2024]
[presidente.utenti.dimessi] la stampa genera pdf e anteprima con link validi per riammissione dei soci

ticket [UOV-648-85282]

**Comment by AlfioEmanueleFresta** [comment]
@GiovanniLongo l'elenco deve essere scaricato in formato Excel dall'apposito pulsante. Non e' prevista la stampa in quel modo in formato PDF. Inoltre il link puo' essere solo aperto da chi ha i permessi per generare l'elenco, quindi passare il PDF ad un terzo non comprometterebbe la sicurezza.
