### ISSUE TITLE
[presidente.utenti.inestensione] genera elenco con estensioni scadute oltre che attive

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#2025]
[presidente.utenti.inestensione] genera elenco con estensioni scadute oltre che attive

es:
Cognome 11236 	Nome 11236 	Comitato Locale Di Genova Ponente: Genova Ponente 	19/03/2014 	19/03/2015
Cognome 19201 	Nome 19201 	Comitato Locale Di Sondrio: Livigno 	11/02/2014 	11/02/2015
Cognome 37483 	Nome 37483 	Comitato Locale Di Campomorone: Campomorone 	30/03/2014 	30/03/2015
Cognome 37483 	Nome 37483 	Comitato Locale Di Genova Ponente: Genova Ponente 	30/03/2014 	30/03/2015
Cognome 37484 	Nome 37484 	Comitato Locale Di Sondrio: Livigno 	10/02/2014 	10/02/2015
Cognome 37910 	Nome 37910 	Comitato Locale Di Sondrio: Livigno 	07/02/2014 	07/02/2015

ticket [OTX-873-30814]

**Comment by dan-it** [comment]
__Terminare estensioni__ nel cronjob non viene eseguito correttamente dal 13 febbraio:
[!!] Routine 'Terminare estensioni' ha fallito (dopo 0.8698s)
     >> Errore: 'EntitÃ  non presente (tabella:id) => '

Strano però che riporti anche estensioni scadute prima di tale data, magari non è (l'unica) causa.

**Comment by AlfioEmanueleFresta** [comment]
Dovrebbe essere risolto. Dovrei aver sbloccato il cron.
