### ISSUE TITLE
utente dimesso mantiene deleghe

### ISSUE THREAD

**Issue by GiovanniLongo** [CroceRossaCatania/gaia#2027]
Dopo dimissioni volontarie senza mantenimento come socio ordinario, il volontario risulta ancora nelle deleghe del comitato e in storico visualizza ancora "Attuale" l'incarico oltre a visualizzare il menù della delega corrispondente e visualizza gestione attività.

Verificato in beta [vol id 110610], non in produzione.

- [x] risoluzione bug
- [x] correzione pregresso

**Comment by AlfioEmanueleFresta** [comment]
- [ ] risoluzione bug
- [ ] correzione pregresso

**Comment by AlfioEmanueleFresta** [comment]
@ico88 bisogna risolvere il pregresso.

**Comment by AlfioEmanueleFresta** [comment]
Pregresso risolto, 51 dimessi disabilitati. Per favore @GiovanniLongo informa gli affetti.
