### ISSUE TITLE
[elettorato] utente non estratto

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2028]
utente 51283 non viene estratto nell'elenco elettorale nonostante rispetti tutti i requisiti per appartenervi.

**Comment by PaoloGiustiniani** [comment]
si aggiunge l'utente 22600 che non viene estratto nè in quello attivo nè in quello passivo e l'utente 41166 in quello passivo.

Appartenenza, stato e date ok.
