### ISSUE TITLE
[stampe] data errata su generazione stampe

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2029]
1954 generando la stampa pdf di estensioni, riserve, etc.. per i volontari segnala che viene sempre riportata la data 17/12/2009 nonostante nelle schede dei vari volontari le date siano corrette e differenti da quella presente. allega nel ticket UBX-108-73622 gli id degli utenti e alcuni pdf generati da gaia riportati la data che in effetti è errata.

**Comment by ico88** [comment]
Data di cosa ?

**Comment by PaoloGiustiniani** [comment]
Riporto la segnalazione integrale dell'utente pervenuta mediante ticket UBX-108-73622 

"Volevo farvi presente che nella stampa di qualsiasi richiesta (estensione, riserva, ecc...) nel testo appare sempre "... volontario dal 17/12/2009..." nonostante nelle schede di ogni singolo volontario siano state inserite le date reali.".
