### ISSUE TITLE
[ufficio soci] procedura termine richiesta mostra descrizione non corretta

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2030]
quando un utente US termina l'estensione di un Volontario la maschera che viene mostrata riporta un testo che fa supporre che la delega che si sta terminando è quella dell'utente che sta eseguendo l'azione, e non dell'utente selezionato.

**Comment by ico88** [comment]
@PaoloGiustiniani guarda e fai pull tu sei il mago dei testi
