### ISSUE TITLE
[quote] eliminazione appartenenza elimina quote

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2031]
al volontario 41778 per fini di supporto è stata eliminata un'appartenenza doppia al comitato. contestualmente a tale eliminazione le sue quote sono state cancellate.

**Comment by ico88** [comment]
@matthewmazzoleni va sistemato manualmente da db

**Comment by matthewmazzoleni** [comment]
@ico88 questo comporta che per ogni anagrafica su cui operiamo (ad esempio errate dimissioni, che sono almeno un paio al giorno) per risistemare la situazione serva necessariamente eliminare la quota del socio. serve qualcosa che permetta di non perdere la quota solo per il fatto di aver cancellato l'appartenenza.

**Comment by AlfioEmanueleFresta** [comment]
La quota e' necessariamente correlata ad un'appartenenza. Senza questa relazione non e' possibile dedurre l'anno di pagamento della quota, o calcolare gli elenchi dei paganti o non paganti, o capire dove la quota e' stata pagata. Si puo' pensare allo spostare contestualmente le quote verso un'altra appartenenza.
