### ISSUE TITLE
Multilingua

### ISSUE THREAD

**Issue by woodybz** [CroceRossaCatania/gaia#2032]
Ciao a tutti e complimenti per il lavoro che state facendo.

Sono Marco, volontario della provincia di Bolzano. Qui da noi ci sono diversi volontari di madrelingua tedesca e che hanno qualche difficoltà con l'italiano.
Io ve la butto lì, ma a giudicare dal codice che avete scritto non mi sembra che possa essere una passeggiata: potrebbe essere pensabile sviluppare il progetto GAIA in multilingua?

Lo so mi starete odiando... 
Una cosa con la quale si potrebbe incominciare e che renderebbe più semplice a tali volontari interagire con GAIA potrebbe essere la traduzione del wiki.
Per i testi, possiamo pensarci noi ed inserirli nelle pagine o farveli avere.

Che ne dite?

**Comment by AlfioEmanueleFresta** [comment]
Gentile @woodybz, grazie per il tuo messaggio.

Questo canale riguarda solo bug e feature approvate -riservato perlopiu' a discussioni tecniche-, per favore scrivi all'indirizzo feedback@gaia.cri.it. 

Potresti indicarci inoltre nel tuo messaggio, qualora in tuo possesso, dati che potrebbero essere utili nel giudicare la richiesta, come 1) il numero di volontari che preferirebbero la lingua tedesca al meglio delle tue conoscenze, 2) i contatti dei volontari che vorrebbero collaborare traducendo il wiki.

Grazie per il tuo feedback!
