### ISSUE TITLE
[elenchi] volontario in estensione presente in elenco dopo il termine

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2033]
il volontario 11261 risulta nell'elenco volontari in estensione all'utente 9552 nonostante l'estensione sia terminata.

**Comment by dan-it** [comment]
Potrebbe essere correlato a  #2025.

**Comment by PaoloGiustiniani** [comment]
Stasera controllo il cron
-----
Croce Rossa Italiana

Paolo Giustiniani


Email.   paolo.giustiniani@cri.it


-----Original Message-----
