### ISSUE TITLE
[estrazione soci] data ingresso CRI si resetta su trasferimento

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2037]
nella procedura di estrazione dei soci la data di inizio appartenenza si resetta ogni volta che il socio
viene trasferito e questa data viene riportata come inizio della "vita in cri" dello stesso.

esempi e replicabilità: PSR-140-65163

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni negli elenchi la data mostrata e' corretta, ho controllato, specialmente negli elenchi soci che vengono usati per le elezioni, quindi tranquillizzalo. Credo da qualche parte appaia la data dell'appartenenza attuale, che lui reputa non debba essere cambiata perche' il trasferimento e' tra unita' dello stesso comitato, ma semplicemente Gaia non funziona cosi'.
