### ISSUE TITLE
[ricevuta] US non riesce ad annullare la ricevuta di un utente

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2050]
l'utente 6059, US di un CL, non riesce ad annullare la quota 267 del 2015 del socio 91788.
nota: per qualche motivo il Socio Ordinario ha due quote pagate nel 2015, una da 8 e una da 16 euro.

rif con dettagli: JON-600-96355

**Comment by ico88** [comment]
@matthewmazzoleni va cancellata quella da 8 immagino no ?

**Comment by matthewmazzoleni** [comment]
@ico88 è scritto sopra, la 267 del 2015.

**Comment by ico88** [comment]
fatto
