### ISSUE TITLE
[permessi] Provinciale può approvare le riserve

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#2051]
Giunge segnalazione mediante ticket QHU-985-38956 che il presidente provinciale 29022 può approvare le richieste di riserva (https://gaia.cri.it/?p=presidente.riserva).

Nello specifico ha la possibilità di approvare o negare la richiesta di riserva 2869.

**Comment by AlfioEmanueleFresta** [comment]
Questa cosa non e' ovviabile fino a Jorvik. Lo declassificherei in quanto il presidente provinciale ha comunque accesso in supervisione (non gli stiamo quindi dando accesso a dati non si sua competenza) e le eventuali azioni vengono comunque tracciate (quindi puo' compiere una azione invalida che viene pero' facilmente riconosciuta come invalida).
