### ISSUE TITLE
[turni] errore su combinazione di operazioni

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2058]
Se si crea il primo turno dell'attività e successivamente si clicca sul tasto rosso "Aggiungi turno", senza clicare prima su "salva", GAIA produce errore.

rif: BVO-888-22003

**Comment by AlfioEmanueleFresta** [comment]
Hm @matthewmazzoleni non riesco a riprodurre. Allo stesso tempo, il tasto "Aggiungi un turno" equivale al tasto Salva, compie solamente delle operazioni in piu' subito dopo.

![image](https://cloud.githubusercontent.com/assets/621062/7917826/09965bf4-0885-11e5-9a85-e08b3b7ef8be.png)
