### ISSUE TITLE
[unità territoriali] NO obiettivi strategici ed aree di intervento

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#2065]
Come da oggetto le unità territoriali non devono avere delegati all'obiettivo strategico o alle aree di intervento.

Tali figure sono possibili unicamente per il Comitato Locale / Provinciale / Regionale.

Il caso è stato riportato tramite ticket più volte.

**Comment by PaoloGiustiniani** [comment]
Richiesta verifica ad Area VI.

**Comment by delbe87** [comment]
credo siamo previsti anche a livello di sede territoriale in base all'art. 24.4 del regolamento dei volontari: "Presso ogni Sede della C.R.I. ove il numero dei Volontari, l’estensione territoriale o la mole delle attività lo giustifichino, il Presidente può individuare i Delegati Tecnici di cui all’articolo 22.1., lettera e, scegliendoli tra i Volontari C.R.I. della Sede medesima."

**Comment by PaoloGiustiniani** [comment]
Stiamo verificando con Area VI @delbe87

**Comment by ico88** [comment]
@PaoloGiustiniani teoricamente sono disponibili anche per le sede afferenti, il V sicuro gli altri credo siano a discrezione del presidente se nominarli o meno
