### ISSUE TITLE
[visibilità dati] visibili titoli di un volontario a cui è stata negata estensione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2066]
se un volontario richiede trasferimento (forse anche estensione) e questo gli viene negato, i suoi titoli sono comunque visibili al comitato presso cui aveva fatto richiesta di trasferimento.

WPL-701-11510

**Comment by ico88** [comment]
Di norma i titoli sono visibili in base al profilo e non solo all'appartenenza. Quale è il comportamento che vogliamo ?

**Comment by PaoloGiustiniani** [comment]
Nel caso in cui un trasferimento/appartenenza sia negata il comitato che ha effettuato tale scelta non dovrà visionare i titoli dell'utente.

**Comment by AlfioEmanueleFresta** [comment]
Questo era riconducibile a #1939. Infatti, lo stato delle appartenenze non era prima discriminato, che fosse volontario, esteso, o estensione negata. @matthewmazzoleni per favore, risolvi il ticket. Grazie.
