### ISSUE TITLE
[corso base] errore in compilazione del verbale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2077]
la situazione di errore è descritta in modo chiaro nel ticket RWB-201-32454
se servissero informazioni aggiuntive dobbiamo chiedere all'utente info precise.

**Comment by AlfioEmanueleFresta** [comment]
Purtroppo non posso indagare la problematica. La segnalazione d'errore e' stata eliminata dal sistema automaticamente e non riesco a riprodurre.
