### ISSUE TITLE
[attività] volontario con appartenenza non riesce ad iscriversi ad attività regionale

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#2086]
Nonostante l'attività sia regionale ed il volontario faccia parte di una provincia della regione non ha la possibilità di iscriversi a quest'ultima.

Tutti i dettagli in LZR-147-89394

**Comment by AlfioEmanueleFresta** [comment]
@PaoloGiustiniani, @delbe87, la volontaria in questione (LZR-147-89394) ha ricevuto conferma dell'appartenenza giorno 6/8, quindi al momento dell'apertura del ticket non era considerata come volontaria del proprio Comitato.
