### ISSUE TITLE
[email] Approvata richiesta trasferimento verso $1

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#2087]
La data di inoltro della richiesta, riportata nella mail, è sempre 01/01/1970

**Comment by AlfioEmanueleFresta** [comment]
@ico88 sembra che delle richieste di trasferimento vengano approvate avendo data di protocollo lasciata vuota (`protData` a NULL).

**Comment by ico88** [comment]
Verifico in serata

**Comment by AlfioEmanueleFresta** [comment]
Aggiungo come nota che la modifica effettuata non e' retroattiva. Sfortunatamente le date inserite in formato non supportato sono andate perse.
