### ISSUE TITLE
[gruppi] l'utente non può abbandonare il gruppo di lavoro

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaCatania/gaia#2088]
L'utente non ha la possibilità, dal menù azioni, di abbandonare il gruppo di lavoro.

Tutte le informazioni nel ticket.
PKD-588-67639
ID 59485

**Comment by PaoloGiustiniani** [comment]
altro caso CNX-157-98392

**Comment by AlfioEmanueleFresta** [comment]
@PaoloGiustiniani e' possibile abbandonare un gruppo solo se, compiendo questa azione, non si rimane senza gruppi di lavoro (leggasi *non si puo' rimanere con meno di un gruppo di lavoro*). Questa scelta progettuale e' stata fatta da /cc @ico88.

**Comment by AlfioEmanueleFresta** [comment]
Con #2089 ho reso la cosa piu' intuitiva, giusto per evitare nuovi casi. Ora appare un pulsante grigio, che al click spiega perche' non e' possibile abbandonare il gruppo di lavoro. 
![image](https://cloud.githubusercontent.com/assets/621062/9197568/1f85b042-402d-11e5-959f-df29ba63b1c4.png)

**Comment by PaoloGiustiniani** [comment]
Non è obbligatorio, da regolamento, partecipare o essere presenti in almeno un gruppo di lavoro.

**Comment by ico88** [comment]
Era stato creato in fase di progetto iniziale in modo che tutti i volontari avevano almeno un gruppo e non potevano rimanere senza, questa cose è così da anni, torna in auge solo ora.
Comunque si può impostare come riteniamo più opportuno, rimuovere questo blocco è estremamente semplice

**Comment by AlfioEmanueleFresta** [comment]
Okay, rimuovo il blocco.
