### ISSUE TITLE
[aspiranti] notifica di corsi non visibili

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2097]
arrivano segnalazioni di aspiranti che, ricevuta la mail di notifica dell'apertura di un nuovo corso, non vedono alcun corso disponibile su GAIA. a seguito di verifica sembra che la condizione sia questa:

- l'aspirante ha visibilità su una o più sedi di un Comitato
- il Comitato di cui sopra attiva un corso in una sede che l'aspirante NON ha tra quelle a lui "attigue" (nel senso di "considerate da GAIA attigue")
- l'aspirante riceve la mail di notifica apertura corso, pur non vedendo fisicamente quella sede.

verificato sue ticket a campione.

**Comment by AlfioEmanueleFresta** [comment]
Grazie @matthewmazzoleni. Da una prima analisi purtroppo non sono riuscito a riprodurre il problema in alcun modo. La query che genera il messaggio e' di fatto la stessa che genera l'elenco dei corsi nelle vicinanze.

Una cosa che mi viene in mente e' che la locazione e' relativa al Corso e non al Comitato, e questa puo' essere rapidamente cambiata. Non vorrei che la locazione del corso sia stata cambiata in itinere e questo ha causato lo scomparire dall'elenco del volontario. Abbiamo modo di verificare, con un presidente o delegato soci, se la posizione del corso e' stata variata?
