### ISSUE TITLE
[email] invio multiplo a volontari in estensione presso altri comitati genera errore

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2103]
quando 6300 esegue quanto in oggetto ottiene:

Rif. errore codice 561652c89b7fd27a527042da

string(812) "Uncaught 20151008132600 [ERR #1003]: Entità non presente (tabella:id) => 	anagrafica:

Backtrace:
[
    {
        "file": "\/home\/gaia\/public_html\/gaia\/core\/class\/Entita.php",
        "line": 115,
        "function": "__construct",
        "class": "Entita",
        "type": "->",
        "args": [
            ""
        ]
    },
    {
        "file": "\/home\/gaia\/public_html\/gaia\/inc\/utente.mail.nuova.ok.php",
        "line": 10,
        "function": "id",
        "class": "Entita",
        "type": "::",
        "args": [
            ""
        ]
    },
    {
        "file": "\/home\/gaia\/public_html\/gaia\/index.php",
        "line": 454,
        "args": [
            "\/home\/gaia\/public_html\/gaia\/inc\/utente.mail.nuova.ok.php"
        ],
        "function": "require"
    }
]
  thrown"

**Comment by ico88** [comment]
@matthewmazzoleni vale per tutti gli estesi o determinati ?
sembrerebbe un errore di db con una appartenenza senza corrispondenza anagrafica
