### ISSUE TITLE
[tesserini] Volontario con tesserino richiesto ma non mostrato a US Regionale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2104]
il volontario 82299 è in stato "Richiesto il 28/12/14" relativamente al tesserino ma non viene mostrato a livello regionale nelle pratiche in lavorazione.

rif: VHS-532-24285

**Comment by PaoloGiustiniani** [comment]
Trattasi di un volontario di Jump la cui richiesta è in carico a US Nazionale.

Si dovranno spostare sul Regionale di competenza *solo* i casi che verranno segnalati.

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni, se @PaoloGiustiniani non ti ha gia' detto, ho provveduto a spostare la richiesta presso l'US Regionale di competenza.
