### ISSUE TITLE
[provvedimenti] errata generazione comunicazione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2107]
nel testo della comunicazione:

il protocollo "200/P/2015/0" appare "200/P/2015/0ERO"
la scritta "contatta il ttuo presidente" dovrebbe essere "contatta il tuo presidente"
appare la scritta "inizio del provvedimento 1444406609"

testo completo in ticket LVP-619-60512

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni risolto
