### ISSUE TITLE
[notifiche] se Presidente approva trasferimento riceve email errata

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2110]
un presidente approva un trasferimento e riceve la mail con il testo che andrebbe inviato ai volontari:

"La tua richiesta di trasferimento presso il Comitato Provinciale Di Bari: Bari inoltrata il 09/10/2015..."

caso: PRP-228-18297

**Comment by ico88** [comment]
Bisogna semplicemente differenziare le mail in modo che al volontario arrivi questa, al presidente del nuovo comitato la notifica, credo superflua la notifica al presidente stesso del comitato uscente che dite @CroceRossaCatania/sviluppatori

**Comment by AlfioEmanueleFresta** [comment]
Concordo con l'inutilita' di notificare al presidente che ha confermato. Allo stesso tempo la notifica va differenziata per il nuovo presidente.
