### ISSUE TITLE
Generare certificati PDF

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaCatania/gaia#2112]
`utente.titolo.certificato`, dato un TitoloPersonale con `corso == true` (non vuoto), deve generare un certificato in PDF. Il certificato di ogni volontario sara' scaricabile dal proprio elenco dei titoli CRI.

I dati sono memorizzati in database su `TitoloPersonale` e sono `luogo`, `pConferma` (esaminatore), `titolo->nome` (nome titolo), `tConferma` (data esame). 

Il lavoro e' iniziato nel branch `issue2112`, con uno scheletro del PDF gia' pronto. Basta solo assegnare a delle variabili all'oggetto PDF i dati in `inc/utente.titolo.certificato.php` e posizionare gli elementi corretti nel certificato tramite HTML/CSS (`core/conf/pdf/modelli/titolocertificato.html`).

**Comment by AlfioEmanueleFresta** [comment]
@ico88 fammi sapere se ti serve altro per procedere.

**Comment by ico88** [comment]
@AlfioEmanueleFresta non riesco a reperire il branch su cui hai lavorato

**Comment by AlfioEmanueleFresta** [comment]
@ico88 `issue2112`.

**Comment by ico88** [comment]
Nada non lo trovo hai pushato ?

**Comment by AlfioEmanueleFresta** [comment]
Si. https://github.com/CroceRossaCatania/gaia/tree/issue2112
`git checkout origin issue2112`

**Comment by ico88** [comment]
Forse no... @AlfioEmanueleFresta 
<img width="485" alt="schermata 2015-11-12 alle 17 24 49" src="https://cloud.githubusercontent.com/assets/3149018/11123855/4e6465b0-8962-11e5-832e-f17732c44b06.png">

**Comment by AlfioEmanueleFresta** [comment]
`git fetch origin` ti scarica tutti i branch, dopodiche' puoi fare `git checkout issue2112`

**Comment by ico88** [comment]
continua a non funzionare, ovvero non trovo le pagine da te indicate

**Comment by AlfioEmanueleFresta** [comment]
https://github.com/CroceRossaCatania/gaia/commit/94d9ad0029ad8faf961a096bc2e0c979e95c879d

**Comment by ico88** [comment]
Non lo metto in dubbio ma sembra che non si aggiorni il mio non trovo le
pagine specificate

**Comment by AlfioEmanueleFresta** [comment]
Il commit elenca le pagine. Se dai `git log` trovi il mio commit? `git status` ti dice che sei sul branch giusto?

**Comment by ico88** [comment]
git status ok, git log non mi sembra corretto

**Comment by AlfioEmanueleFresta** [comment]
Tutto risolto sulla tua macchina di sviluppo.

**Comment by ico88** [comment]
Confermo
Grazie
