### ISSUE TITLE
[corsi base] presidente riceve errore su apertura

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaCatania/gaia#2116]
Quando il presidente 4845 apre un nuovo corso base dopo aver inserito la sede e la data riceve la schermate "Ooops qualcosa è andato storto.."

564b30709b7fd201216c41f9

string(110) "Uncaught 20151117144936 [ERR #1003]: Entità non presente (tabella:id) => 	comitati:1508

**Comment by AlfioEmanueleFresta** [comment]
Era rimasta una area associata al comitato 1508. Eliminata. Ora funziona. @matthewmazzoleni
