### ISSUE TITLE
Rivoluzione copernicana

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaCatania/gaia#793]
Si parte con la completa ristrutturazione del sistema dei comitati per risolvere l'annoso problema dei fake locali. Le cose da fare sono:

* @AlfioEmanueleFresta  : realizzare un selettore di geoentità che permetta di selezionare geoentità di ogni tipo e che possa partire da un livello dato tipo 
 ```html
<a data-selettore-comitato="Regionale:1" 
    data-selettore-livello="Regionale,Provinciale,Locale">
        Clicca miao
</a>
```

* @luca-dex : ristrutturare tutto il codice delle geoentità basandolo su geoentità e non coi voncoli che sopra comitato ci sia locale

* @luca-dex : preparare script di migrazione di un comitato sotto un provinciale o un regionale che si occupi di trasferire tutto quello che serve trasferire (delegati, ecc)

Lunga vita e prosperità e che la forza sia con voi

**Comment by AlfioEmanueleFresta** [comment]
In Jorvik.
